# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1404 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.h2o_mmr=[[  0.99952170066954491E-003],]
input.mbar=[[  0.28966000000000001E+002],]
input.ncol=[[         4],]
input.pcols=[[         4],]
input.pver=[[        72],]
input.adv_mass_h2o=[[  0.18000000000000000E+002],]
# Output data is stored here.
output = Object()
output.h2o_vmr=[[  0.16084525323107799E-002],]
