# Data at [lat=  -13.2292708024991      , lon=   139.817062054960      , k=          51 , time step=         355 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.calday=[[  0.15791666666666666E+002],]
input.clat=[[ -0.23209247021928292E+000],]
input.clon=[[  0.24529309132449177E+001],]
input.ncol=[[         4],]
# Output data is stored here.
output = Object()
output.coszrs=[[ -0.29256165507930343E+000],]
