# Data at [lat=   27.8859484222059      , lon=   83.8815732902265      , k=          44 , time step=        1410 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.Temperature=[[-0.3575495987E+02],]
input.w_vlc=[[ 0.2000000000E+00],]
input.Ns=[[ 0.1542388755E-01],]
# Output data is stored here.
output = Object()
output.Nis=[[ 0.1542388755E-01],]
output.Nid=[[ 0.0000000000E+00],]
