# Data at [lat=   39.0553303768561      , lon=   352.440165015397      , k=          37 , time step=        1404 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.Temperature=[[-0.5714452694E+02],]
input.w_vlc=[[ 0.2000000000E+00],]
input.RH=[[ 0.7452682855E+00],]
input.Na=[[ 0.5353090275E+01],]
# Output data is stored here.
output = Object()
output.Ni=[[ 0.0000000000E+00],]
