# Data at [lat=   71.9201421331276      , lon=   71.5690366721838      , k=          62 , time step=        1403 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.Temperature=[[-0.3694781043E+02],]
input.w_vlc=[[ 0.2000000000E+00],]
input.RH=[[ 0.8297163298E+00],]
input.Na=[[ 0.5901113453E+02],]
input.subgrid=[[ 0.1200000000E+01],]
# Output data is stored here.
output = Object()
output.Ni=[[ 0.0000000000E+00],]
