# Data at [lat=   27.8859484222059      , lon=   83.8815732902265      , k=          44 , time step=        1410 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.wbar=[[ 0.2000000000E+00],]
input.tair=[[ 0.2373950401E+03],]
input.pmid=[[ 0.3691236844E+05],]
input.relhum=[[ 0.7092935911E+00],]
input.cldn=[[ 0.9990000000E+00],]
input.rhoair=[[ 0.5416944083E+00],]
input.so4_num=[[ 0.1045423629E+02],]
input.dst3_num=[[ 0.1542388755E-01],]
# Output data is stored here.
output = Object()
output.nuci=[[ 0.2847341106E+05],]
output.onihf=[[ 0.0000000000E+00],]
output.oniimm=[[ 0.2847341106E+05],]
output.onidep=[[ 0.0000000000E+00],]
output.onimey=[[ 0.0000000000E+00],]
