# Data at [lat=   39.0553303768561      , lon=   352.440165015397      , k=          37 , time step=        1406 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.wbar=[[ 0.2000000000E+00],]
input.tair=[[ 0.2162291542E+03],]
input.pmid=[[ 0.2345738215E+05],]
input.relhum=[[ 0.7628700627E+00],]
input.cldn=[[ 0.3316474520E+00],]
input.rhoair=[[ 0.3779369685E+00],]
input.so4_num=[[ 0.5303462857E+01],]
input.dst3_num=[[ 0.2117117105E-02],]
input.subgrid=[[ 0.1200000000E+01],]
# Output data is stored here.
output = Object()
output.nuci=[[ 0.1396028040E+07],]
output.onihf=[[ 0.1396028040E+07],]
output.oniimm=[[ 0.0000000000E+00],]
output.onidep=[[ 0.0000000000E+00],]
output.onimey=[[ 0.0000000000E+00],]
