# Data at [lat=   71.9201421331276      , lon=   71.5690366721838      , k=          62 , time step=        1403 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.wbar=[[ 0.2000000000E+00],]
input.tair=[[ 0.2369643763E+03],]
input.pmid=[[ 0.9134903010E+05],]
input.relhum=[[ 0.8297163298E+00],]
input.cldn=[[ 0.9990000000E+00],]
input.rhoair=[[ 0.1342996745E+01],]
input.so4_num=[[ 0.5901113453E+02],]
input.dst3_num=[[ 0.8633937165E-03],]
# Output data is stored here.
output = Object()
output.nuci=[[ 0.0000000000E+00],]
output.onihf=[[ 0.0000000000E+00],]
output.oniimm=[[ 0.6428859336E+03],]
output.onidep=[[ 0.0000000000E+00],]
output.onimey=[[ 0.0000000000E+00],]
