# Data at [lat=  -13.2292708024991      , lon=   139.817062054960      , k=          47 , time step=         355 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.xl=[[ 0.2045167481E-07],]
input.cldnum=[[ 0.2145049148E+08],]
input.cfact=[[ 0.6799056796E-03],]
input.cldfrc=[[ 0.7653835562E+00],]
input.tfld=[[ 0.2704710575E+03],]
input.press=[[ 0.5280266906E+05],]
# Output data is stored here.
output = Object()
output.uptkrate=[[ 0.2745894165E-01],]
