# Data at [lat=  -13.2292708024991      , lon=   139.817062054960      , k=          47 , time step=         355 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.cldfrc=[[ 0.7653835562E+00],]
input.qcw=[[ 0.0000000000E+00, 0.0000000000E+00, 0.0000000000E+00, 0.0000000000E+00, 0.0000000000E+00, 0.0000000000E+00, 0.1821296430E-10, 0.2432565542E-10, 0.2454017849E-09, 0.3567337656E-11, 0.4159584725E-13, 0.8950397033E-12, 0.3594812481E-16, 0.4818129270E+09, 0.7580693633E-13, 0.2408959105E-11, 0.8383888225E-17, 0.4271204856E-21, 0.1648792032E+08, 0.1141617399E-12, 0.6886564669E-11, 0.1137264049E-11, 0.3791380267E-12, 0.2311807532E-11, 0.1340284959E-10, 0.4317459265E-17, 0.8085661862E+05, 0.0000000000E+00, 0.0000000000E+00, 0.0000000000E+00, 0.0000000000E+00,],]
input.lwc=[[ 0.2302286341E-04],]
input.cfact=[[ 0.6799056796E-03],]
input.ncol=[[         4],]
input.loffset=[[         9],]
# Output data is stored here.
output = Object()
output.conc_obj%xlwc=[[ 0.2045167481E-07],]
output.conc_obj%so4c=[[ 0.1942603528E-10],]
