# Data at [lat=  -13.2292708024991      , lon=   139.817062054960      , k=          47 , time step=         355 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.tmr=[[ 0.7580693633E-13],]
input.dqdt=[[ 0.1165423949E-16],]
input.dtime=[[ 0.3600000000E+04],]
# Output data is stored here.
output = Object()
output.tmr=[[ 0.1177621985E-12],]
