# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1402 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.ncol=[[         4],]
input.dt=[[  0.36000000000000000E+004],]
input.sed_vel=[[  0.14613429767747538E-002],]
input.qq_in=[[  0.94354839590997718E-013],]
input.rho=[[  0.10104512957066121E+001],]
input.tair=[[  0.25385187022866876E+003],]
input.pint=[[  0.72391323778787599E+005],]
input.pmid=[[  0.73627774066186757E+005],]
input.pdel=[[  0.24729005747983465E+004],]
input.pcols=[[         4],]
input.pver=[[        72],]
input.pverp=[[        73],]
input.gravit=[[  0.98061600000000002E+001],]
# Output data is stored here.
output = Object()
output.dqdt_sed=[[ -0.43563751065140679E-018],]
output.sflx=[[  0.23358578501522557E-014],]
