# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1408 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.ncol=[[         4],]
input.dt=[[  0.36000000000000000E+004],]
input.sed_vel=[[  0.40691567123299759E-004],]
input.qq_in=[[  0.45159183487076291E-011],]
input.rho=[[  0.10216506497207014E+001],]
input.tair=[[  0.25184386909617683E+003],]
input.pint=[[  0.72613451271108061E+005],]
input.pmid=[[  0.73854968428838663E+005],]
input.pdel=[[  0.24830343154612056E+004],]
input.pcols=[[         4],]
input.pver=[[        72],]
input.pverp=[[        73],]
input.gravit=[[  0.98061600000000002E+001],]
# Output data is stored here.
output = Object()
output.dqdt_sed=[[ -0.31706989419849519E-018],]
output.sflx=[[  0.82432507671620743E-014],]
