# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1405 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.ncol=[[         4],]
input.dt=[[  0.36000000000000000E+004],]
input.sed_vel=[[  0.14724516650372417E-005],]
input.qq_in=[[  0.38671503686771520E-013],]
input.rho=[[  0.10162683776962529E+001],]
input.tair=[[  0.25275054215293568E+003],]
input.pint=[[  0.72491633820414849E+005],]
input.pmid=[[  0.73730372244093567E+005],]
input.pdel=[[  0.24774768473574659E+004],]
input.pcols=[[         4],]
input.pver=[[        72],]
input.pverp=[[        73],]
input.gravit=[[  0.98061600000000002E+001],]
# Output data is stored here.
output = Object()
output.dqdt_sed=[[ -0.12407657273874970E-022],]
output.sflx=[[  0.14622194892871600E-015],]
