# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1400 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.ncol=[[         4],]
input.dt=[[  0.36000000000000000E+004],]
input.sed_vel=[[  0.14731824588160695E-002],]
input.qq_in=[[  0.25298528346991238E-011],]
input.rho=[[  0.10072025410912551E+001],]
input.tair=[[  0.25467953091539104E+003],]
input.pint=[[  0.72393826956975259E+005],]
input.pmid=[[  0.73630334343471710E+005],]
input.pdel=[[  0.24730147729929158E+004],]
input.pcols=[[         4],]
input.pver=[[        72],]
input.pverp=[[        73],]
input.gravit=[[  0.98061600000000002E+001],]
# Output data is stored here.
output = Object()
output.dqdt_sed=[[ -0.99869091079188210E-017],]
output.sflx=[[  0.14283237202187976E-012],]
