# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1415 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.ncol=[[         4],]
input.dt=[[  0.36000000000000000E+004],]
input.sed_vel=[[  0.16189269695923424E-004],]
input.qq_in=[[  0.29168297148968473E-009],]
input.rho=[[  0.10223747873618645E+001],]
input.tair=[[  0.25153076563850570E+003],]
input.pint=[[  0.72574795971527099E+005],]
input.pmid=[[  0.73815431377122688E+005],]
input.pdel=[[  0.24812708111911925E+004],]
input.pcols=[[         4],]
input.pver=[[        72],]
input.pverp=[[        73],]
input.gravit=[[  0.98061600000000002E+001],]
# Output data is stored here.
output = Object()
output.dqdt_sed=[[  0.46393982794810292E-016],]
output.sflx=[[  0.21681802251229618E-011],]
