# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1410 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.ncol=[[         4],]
input.dt=[[  0.36000000000000000E+004],]
input.sed_vel=[[  0.70241157931095807E-002],]
input.qq_in=[[  0.18503403050037248E-010],]
input.rho=[[  0.10213089106025375E+001],]
input.tair=[[  0.25186794733003740E+003],]
input.pint=[[  0.72596199279596112E+005],]
input.pmid=[[  0.73837322908353613E+005],]
input.pdel=[[  0.24822472575150168E+004],]
input.pcols=[[         4],]
input.pver=[[        72],]
input.pverp=[[        73],]
input.gravit=[[  0.98061600000000002E+001],]
# Output data is stored here.
output = Object()
output.dqdt_sed=[[ -0.70569430779612174E-016],]
output.sflx=[[  0.00000000000000000E+000],]
