# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1407 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.ncol=[[         4],]
input.dt=[[  0.36000000000000000E+004],]
input.sed_vel=[[  0.70177668630513430E-002],]
input.qq_in=[[  0.58550574648556666E-011],]
input.rho=[[  0.10198781758458073E+001],]
input.tair=[[  0.25215295026150088E+003],]
input.pint=[[  0.72576642001523782E+005],]
input.pmid=[[  0.73817319516245640E+005],]
input.pdel=[[  0.24813550294437155E+004],]
input.pcols=[[         4],]
input.pver=[[        72],]
input.pverp=[[        73],]
input.gravit=[[  0.98061600000000002E+001],]
# Output data is stored here.
output = Object()
output.dqdt_sed=[[  0.20080494333399042E-014],]
output.sflx=[[  0.31929813882983028E-021],]
