# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1414 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.ncol=[[         4],]
input.dt=[[  0.36000000000000000E+004],]
input.sed_vel=[[  0.70315750678648769E-002],]
input.qq_in=[[  0.74987456613798337E-012],]
input.rho=[[  0.10219893278665666E+001],]
input.tair=[[  0.25153838282546428E+003],]
input.pint=[[  0.72549771171952743E+005],]
input.pmid=[[  0.73789835745846271E+005],]
input.pdel=[[  0.24801291477870836E+004],]
input.pcols=[[         4],]
input.pver=[[        72],]
input.pverp=[[        73],]
input.gravit=[[  0.98061600000000002E+001],]
# Output data is stored here.
output = Object()
output.dqdt_sed=[[ -0.59757705854284029E-017],]
output.sflx=[[  0.00000000000000000E+000],]
