# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1406 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.ncol=[[         4],]
input.dt=[[  0.36000000000000000E+004],]
input.sed_vel=[[  0.70284074409137671E-006],]
input.qq_in=[[  0.17650513908965776E+010],]
input.rho=[[  0.10182541042230193E+001],]
input.tair=[[  0.25240041995122448E+003],]
input.pint=[[  0.72532433392349703E+005],]
input.pmid=[[  0.73772102480388843E+005],]
input.pdel=[[  0.24793381760783086E+004],]
input.pcols=[[         4],]
input.pver=[[        72],]
input.pverp=[[        73],]
input.gravit=[[  0.98061600000000002E+001],]
# Output data is stored here.
output = Object()
output.dqdt_sed=[[  0.72237211206388396E+000],]
output.sflx=[[  0.30690541476184588E+008],]
