# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1401 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.ncol=[[         4],]
input.dt=[[  0.36000000000000000E+004],]
input.sed_vel=[[  0.69705635873254018E-002],]
input.qq_in=[[  0.84244580909337147E-012],]
input.rho=[[  0.10087665775526036E+001],]
input.tair=[[  0.25429567378100737E+003],]
input.pint=[[  0.72396943703549943E+005],]
input.pmid=[[  0.73633522185031456E+005],]
input.pdel=[[  0.24731569629630394E+004],]
input.pcols=[[         4],]
input.pver=[[        72],]
input.pverp=[[        73],]
input.gravit=[[  0.98061600000000002E+001],]
# Output data is stored here.
output = Object()
output.dqdt_sed=[[  0.63904817988627873E-016],]
output.sflx=[[  0.00000000000000000E+000],]
