# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1411 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.ncol=[[         4],]
input.dt=[[  0.36000000000000000E+004],]
input.sed_vel=[[  0.70231589238268820E-002],]
input.qq_in=[[  0.50461292858417024E-011],]
input.rho=[[  0.10208140660397955E+001],]
input.tair=[[  0.25191209535514304E+003],]
input.pint=[[  0.72573869102084544E+005],]
input.pmid=[[  0.73814483365194654E+005],]
input.pdel=[[  0.24812285262202349E+004],]
input.pcols=[[         4],]
input.pver=[[        72],]
input.pverp=[[        73],]
input.gravit=[[  0.98061600000000002E+001],]
# Output data is stored here.
output = Object()
output.dqdt_sed=[[ -0.84920565372973499E-017],]
output.sflx=[[  0.00000000000000000E+000],]
