# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1409 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.ncol=[[         4],]
input.dt=[[  0.36000000000000000E+004],]
input.sed_vel=[[  0.18007691997492762E-005],]
input.qq_in=[[  0.62938026345554471E+008],]
input.rho=[[  0.10224555163980475E+001],]
input.tair=[[  0.25167660719924228E+003],]
input.pint=[[  0.72622342779770013E+005],]
input.pmid=[[  0.73864062758506552E+005],]
input.pdel=[[  0.24834399574731069E+004],]
input.pcols=[[         4],]
input.pver=[[        72],]
input.pverp=[[        73],]
input.gravit=[[  0.98061600000000002E+001],]
# Output data is stored here.
output = Object()
output.dqdt_sed=[[ -0.46659354339276191E-001],]
output.sflx=[[  0.34819585159670017E+007],]
