# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          30 , time step=        1402 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.pmid=[[  0.75355335897260984E+004],]
input.pmid_p1=[[  0.81946275124734711E+004],]
input.pmid_m1=[[  0.68476390229712551E+004],]
input.zm=[[  0.16893543986851761E+005],]
input.zm_p1=[[  0.16382871289147142E+005],]
input.zm_m1=[[  0.17478346144733641E+005],]
input.tropLev=[[        23],]
input.tropZ=[[  0.17065406848281349E+005],]
# Output data is stored here.
output = Object()
output.tropopause_interpolateP=[[  0.75365058496766169E+004],]
