# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          30 , time step=        1414 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.pmid=[[  0.23341922137057227E+005],]
input.pmid_p1=[[  0.25235446534503626E+005],]
input.pmid_m1=[[  0.21596715592703345E+005],]
input.temp=[[  0.21744663142238204E+003],]
input.temp_p1=[[  0.21871763583054664E+003],]
input.temp_m1=[[  0.21663206183310771E+003],]
input.tropLev=[[        37],]
input.tropP=[[  0.23150165210106839E+005],]
# Output data is stored here.
output = Object()
output.tropopause_interpolateT=[[  0.21736016305347573E+003],]
