# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          30 , time step=        1415 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.pmid=[[  0.23344295377792649E+005],]
input.pint=[[  0.22435705993882915E+005],]
input.pint_p1=[[  0.24252884761702382E+005],]
input.zm=[[  0.98258545847484893E+004],]
input.zi=[[  0.10073523280562235E+005],]
input.zi_p1=[[  0.95781858889347423E+004],]
input.tropP=[[  0.23118814591518414E+005],]
# Output data is stored here.
output = Object()
output.tropopause_interpolateZ=[[  0.98864063630946366E+004],]
