# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          30 , time step=        1416 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.pmid=[[  0.23349090963618077E+005],]
input.pint=[[  0.22439656823392372E+005],]
input.pint_p1=[[  0.24258525103843778E+005],]
input.zm=[[  0.98274327378041689E+004],]
input.zi=[[  0.10075189849851697E+005],]
input.zi_p1=[[  0.95796756257566412E+004],]
input.tropP=[[  0.23085925671607754E+005],]
# Output data is stored here.
output = Object()
output.tropopause_interpolateZ=[[  0.98981204916800016E+004],]
