# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          30 , time step=        1405 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.pmid=[[  0.23336408649106626E+005],]
input.pmid_p1=[[  0.25227908073143251E+005],]
input.pmid_m1=[[  0.21593068464049695E+005],]
input.temp=[[  0.21797991034665040E+003],]
input.temp_p1=[[  0.21912090189033285E+003],]
input.temp_m1=[[  0.21725523635617617E+003],]
input.tropLev=[[        37],]
input.tropP=[[  0.23620856498109231E+005],]
# Output data is stored here.
output = Object()
output.tropopause_interpolateT=[[  0.21815727983666295E+003],]
