# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          30 , time step=        1413 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.pmid=[[  0.23341543301571568E+005],]
input.pmid_p1=[[  0.25234928561725566E+005],]
input.pmid_m1=[[  0.21596464996027131E+005],]
input.temp=[[  0.21747938818434565E+003],]
input.temp_p1=[[  0.21874490408588574E+003],]
input.temp_m1=[[  0.21666961189342786E+003],]
input.tropLev=[[        37],]
input.tropP=[[  0.23170659336158518E+005],]
# Output data is stored here.
output = Object()
output.tropopause_interpolateT=[[  0.21740281408981829E+003],]
