# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          30 , time step=        1404 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.pmid=[[  0.23332366781697390E+005],]
input.pint=[[  0.22425878654497254E+005],]
input.pint_p1=[[  0.24238854908897527E+005],]
input.zm=[[  0.98359543285698546E+004],]
input.zi=[[  0.10083920144618982E+005],]
input.zi_p1=[[  0.95879885125207256E+004],]
input.tropP=[[  0.23649005040036354E+005],]
# Output data is stored here.
output = Object()
output.tropopause_interpolateZ=[[  0.97482611735599494E+004],]
