# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          30 , time step=        1405 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.pmid=[[  0.23336408649106626E+005],]
input.pint=[[  0.22429208535269914E+005],]
input.pint_p1=[[  0.24243608762943339E+005],]
input.zm=[[  0.98354349065032766E+004],]
input.zi=[[  0.10083482866298615E+005],]
input.zi_p1=[[  0.95873869467079367E+004],]
input.tropP=[[  0.23620856498109231E+005],]
# Output data is stored here.
output = Object()
output.tropopause_interpolateZ=[[  0.97566379044877431E+004],]
