# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          30 , time step=        1412 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.pmid=[[  0.23341804659900656E+005],]
input.pmid_p1=[[  0.25235285910772614E+005],]
input.pmid_m1=[[  0.21596637882493815E+005],]
input.temp=[[  0.21749995360049982E+003],]
input.temp_p1=[[  0.21875950127000362E+003],]
input.temp_m1=[[  0.21669426741400838E+003],]
input.tropLev=[[        37],]
input.tropP=[[  0.23191106992722605E+005],]
# Output data is stored here.
output = Object()
output.tropopause_interpolateT=[[  0.21743279891015280E+003],]
