# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          30 , time step=        1410 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.pmid=[[  0.23346325172374269E+005],]
input.pmid_p1=[[  0.25241466700304896E+005],]
input.pmid_m1=[[  0.21599628165726397E+005],]
input.temp=[[  0.21760502642469677E+003],]
input.temp_p1=[[  0.21884402513491443E+003],]
input.temp_m1=[[  0.21681608191039925E+003],]
input.tropLev=[[        37],]
input.tropP=[[  0.23275363957331690E+005],]
# Output data is stored here.
output = Object()
output.tropopause_interpolateT=[[  0.21757414238664876E+003],]
