# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          30 , time step=        1404 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.pmid=[[  0.23332366781697390E+005],]
input.pmid_p1=[[  0.25222381723659713E+005],]
input.pmid_m1=[[  0.21590394800739905E+005],]
input.temp=[[  0.21804111839202363E+003],]
input.temp_p1=[[  0.21917292759118035E+003],]
input.temp_m1=[[  0.21732082510057637E+003],]
input.tropLev=[[        37],]
input.tropP=[[  0.23649005040036354E+005],]
# Output data is stored here.
output = Object()
output.tropopause_interpolateT=[[  0.21823698683483852E+003],]
