# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          30 , time step=        1403 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.pmid=[[  0.23329055374482632E+005],]
input.pint=[[  0.22423150561242721E+005],]
input.pint_p1=[[  0.24234960187722547E+005],]
input.zm=[[  0.98377699655299548E+004],]
input.zi=[[  0.10085683926538817E+005],]
input.zi_p1=[[  0.95898560045210943E+004],]
input.tropP=[[  0.23657617481883681E+005],]
# Output data is stored here.
output = Object()
output.tropopause_interpolateZ=[[  0.97467588854278547E+004],]
