# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          30 , time step=        1407 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.pmid=[[  0.23344470447070384E+005],]
input.pmid_p1=[[  0.25238930778368958E+005],]
input.pmid_m1=[[  0.21598401279613456E+005],]
input.temp=[[  0.21786033067140957E+003],]
input.temp_p1=[[  0.21903439783362586E+003],]
input.temp_m1=[[  0.21711957266929016E+003],]
input.tropLev=[[        37],]
input.tropP=[[  0.23515898283148617E+005],]
# Output data is stored here.
output = Object()
output.tropopause_interpolateT=[[  0.21797042188404001E+003],]
