# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          30 , time step=        1408 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.pmid=[[  0.23347961274549700E+005],]
input.pint=[[  0.22438726132321390E+005],]
input.pint_p1=[[  0.24257196416778010E+005],]
input.zm=[[  0.98394564677246890E+004],]
input.zi=[[  0.10087721090116029E+005],]
input.zi_p1=[[  0.95911918453333492E+004],]
input.tropP=[[  0.23447007719782399E+005],]
# Output data is stored here.
output = Object()
output.tropopause_interpolateZ=[[  0.98119471263279411E+004],]
