# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          30 , time step=        1412 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.pmid=[[  0.68476390229712551E+004],]
input.pmid_p1=[[  0.75355335897260984E+004],]
input.pmid_m1=[[  0.61015181670369457E+004],]
input.zm=[[  0.17484637411409640E+005],]
input.zm_p1=[[  0.16897815630434656E+005],]
input.zm_m1=[[  0.18192310448890221E+005],]
input.tropLev=[[        22],]
input.tropZ=[[  0.17290685483427620E+005],]
# Output data is stored here.
output = Object()
output.tropopause_interpolateP=[[  0.68486711673363925E+004],]
