# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          30 , time step=        1409 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.pmid=[[  0.23348804505700991E+005],]
input.pint=[[  0.22439420825866058E+005],]
input.pint_p1=[[  0.24258188185535924E+005],]
input.zm=[[  0.98388597915296996E+004],]
input.zi=[[  0.10087055377660108E+005],]
input.zi_p1=[[  0.95906642053992909E+004],]
input.tropP=[[  0.23363359158810297E+005],]
# Output data is stored here.
output = Object()
output.tropopause_interpolateZ=[[  0.98348118269393417E+004],]
