# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          30 , time step=        1417 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.pmid=[[  0.23351937115025838E+005],]
input.pint=[[  0.22442001616996222E+005],]
input.pint_p1=[[  0.24261872613055457E+005],]
input.zm=[[  0.98268653168791789E+004],]
input.zi=[[  0.10074604104791935E+005],]
input.zi_p1=[[  0.95791265289664243E+004],]
input.tropP=[[  0.23043664838171419E+005],]
# Output data is stored here.
output = Object()
output.tropopause_interpolateZ=[[  0.99096973421679504E+004],]
