# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          30 , time step=        1406 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.pmid=[[  0.23340277899120636E+005],]
input.pmid_p1=[[  0.25233198406954732E+005],]
input.pmid_m1=[[  0.21595627942318381E+005],]
input.temp=[[  0.21791856653305865E+003],]
input.temp_p1=[[  0.21907399304226831E+003],]
input.temp_m1=[[  0.21718741141264044E+003],]
input.tropLev=[[        37],]
input.tropP=[[  0.23575232569665004E+005],]
# Output data is stored here.
output = Object()
output.tropopause_interpolateT=[[  0.21806697559095977E+003],]
