# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          30 , time step=        1402 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.pmid=[[  0.23326895690720907E+005],]
input.pmid_p1=[[  0.25214901230676893E+005],]
input.pmid_m1=[[  0.21586775717349163E+005],]
input.temp=[[  0.21814827265853211E+003],]
input.temp_p1=[[  0.21928027049676572E+003],]
input.temp_m1=[[  0.21742902407305030E+003],]
input.tropLev=[[        37],]
input.tropP=[[  0.23642784815680850E+005],]
# Output data is stored here.
output = Object()
output.tropopause_interpolateT=[[  0.21834391491281929E+003],]
