# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          30 , time step=        1406 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.pmid=[[  0.23340277899120636E+005],]
input.pint=[[  0.22432396205700865E+005],]
input.pint_p1=[[  0.24248159592540404E+005],]
input.zm=[[  0.98357697061597446E+004],]
input.zi=[[  0.10083893033753446E+005],]
input.zi_p1=[[  0.95876463785660435E+004],]
input.tropP=[[  0.23575232569665004E+005],]
# Output data is stored here.
output = Object()
output.tropopause_interpolateZ=[[  0.97706431140341192E+004],]
