# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          30 , time step=        1411 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.pmid=[[  0.23344207477615426E+005],]
input.pmid_p1=[[  0.25238571226467709E+005],]
input.pmid_m1=[[  0.21598227327399756E+005],]
input.temp=[[  0.21754763090258592E+003],]
input.temp_p1=[[  0.21879648011907821E+003],]
input.temp_m1=[[  0.21674817117039728E+003],]
input.tropLev=[[        37],]
input.tropP=[[  0.23228885199313758E+005],]
# Output data is stored here.
output = Object()
output.tropopause_interpolateT=[[  0.21749670083170625E+003],]
