# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          30 , time step=        1411 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.pmid=[[  0.23344207477615426E+005],]
input.pint=[[  0.22435633577576191E+005],]
input.pint_p1=[[  0.24252781377654661E+005],]
input.zm=[[  0.98325209183314128E+004],]
input.zi=[[  0.10080368952473797E+005],]
input.zi_p1=[[  0.95846728841890272E+004],]
input.tropP=[[  0.23228885199313758E+005],]
# Output data is stored here.
output = Object()
output.tropopause_interpolateZ=[[  0.98634396374893877E+004],]
