# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          30 , time step=        1416 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.pmid=[[  0.23349090963618077E+005],]
input.pmid_p1=[[  0.25245248301100819E+005],]
input.pmid_m1=[[  0.21601457714749751E+005],]
input.temp=[[  0.21730774460717379E+003],]
input.temp_p1=[[  0.21859495974797062E+003],]
input.temp_m1=[[  0.21647418748172734E+003],]
input.tropLev=[[        37],]
input.tropP=[[  0.23085925671607754E+005],]
# Output data is stored here.
output = Object()
output.tropopause_interpolateT=[[  0.21718629705788669E+003],]
