# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          30 , time step=        1402 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.pmid=[[  0.23326895690720907E+005],]
input.pint=[[  0.22421371312023224E+005],]
input.pint_p1=[[  0.24232420069418593E+005],]
input.zm=[[  0.98407818778907404E+004],]
input.zi=[[  0.10088663874478276E+005],]
input.zi_p1=[[  0.95928998813032049E+004],]
input.tropP=[[  0.23642784815680850E+005],]
# Output data is stored here.
output = Object()
output.tropopause_interpolateZ=[[  0.97532328022660877E+004],]
