# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          30 , time step=        1400 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.pmid=[[  0.23327133081011500E+005],]
input.pint=[[  0.22421566885327396E+005],]
input.pint_p1=[[  0.24232699276695603E+005],]
input.zm=[[  0.98515494652646976E+004],]
input.zi=[[  0.10099514681563209E+005],]
input.zi_p1=[[  0.96035842489661845E+004],]
input.tropP=[[  0.23595333341721096E+005],]
# Output data is stored here.
output = Object()
output.tropopause_interpolateZ=[[  0.97771205862489242E+004],]
