# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          30 , time step=        1417 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.pmid=[[  0.23351937115025838E+005],]
input.pmid_p1=[[  0.25249139776443732E+005],]
input.pmid_m1=[[  0.21603340421385714E+005],]
input.temp=[[  0.21719844571873094E+003],]
input.temp_p1=[[  0.21849514564724322E+003],]
input.temp_m1=[[  0.21635320017061491E+003],]
input.tropLev=[[        37],]
input.tropP=[[  0.23043664838171419E+005],]
# Output data is stored here.
output = Object()
output.tropopause_interpolateT=[[  0.21705412828168596E+003],]
