# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          30 , time step=        1412 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.pmid=[[  0.23341804659900656E+005],]
input.pint=[[  0.22433654023152823E+005],]
input.pint_p1=[[  0.24249955296648488E+005],]
input.zm=[[  0.98291314527629384E+004],]
input.zi=[[  0.10076835179278849E+005],]
input.zi_p1=[[  0.95814277262470277E+004],]
input.tropP=[[  0.23191106992722605E+005],]
# Output data is stored here.
output = Object()
output.tropopause_interpolateZ=[[  0.98695609354524022E+004],]
