# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          30 , time step=        1414 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.pmid=[[  0.23341922137057227E+005],]
input.pint=[[  0.22433750806368422E+005],]
input.pint_p1=[[  0.24250093467746028E+005],]
input.zm=[[  0.98263426656848096E+004],]
input.zi=[[  0.10073989979592652E+005],]
input.zi_p1=[[  0.95786953517769653E+004],]
input.tropP=[[  0.23150165210106839E+005],]
# Output data is stored here.
output = Object()
output.tropopause_interpolateZ=[[  0.98778202382702602E+004],]
