# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          30 , time step=        1401 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.pmid=[[  0.23327428659400091E+005],]
input.pint=[[  0.22421810396727778E+005],]
input.pint_p1=[[  0.24233046922072404E+005],]
input.zm=[[  0.98467328208484050E+004],]
input.zi=[[  0.10094683797812117E+005],]
input.zi_p1=[[  0.95987818438846934E+004],]
input.tropP=[[  0.23621697863262270E+005],]
# Output data is stored here.
output = Object()
output.tropopause_interpolateZ=[[  0.97651239574898809E+004],]
