# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          30 , time step=        1407 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.pmid=[[  0.23344470447070384E+005],]
input.pint=[[  0.22435850224200931E+005],]
input.pint_p1=[[  0.24253090669939837E+005],]
input.zm=[[  0.98373245700601801E+004],]
input.zi=[[  0.10085538788972610E+005],]
input.zi_p1=[[  0.95891103511477522E+004],]
input.tropP=[[  0.23515898283148617E+005],]
# Output data is stored here.
output = Object()
output.tropopause_interpolateZ=[[  0.97897632637683255E+004],]
