# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          30 , time step=        1409 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.pmid=[[  0.23348804505700991E+005],]
input.pmid_p1=[[  0.25244856633982170E+005],]
input.pmid_m1=[[  0.21601268225104206E+005],]
input.temp=[[  0.21770151500576378E+003],]
input.temp_p1=[[  0.21891755959606428E+003],]
input.temp_m1=[[  0.21692959935817552E+003],]
input.tropLev=[[        37],]
input.tropP=[[  0.23363359158810297E+005],]
# Output data is stored here.
output = Object()
output.tropopause_interpolateT=[[  0.21771122078022358E+003],]
