# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          30 , time step=        1400 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.pmid=[[  0.23327133081011500E+005],]
input.pmid_p1=[[  0.25215225808793144E+005],]
input.pmid_m1=[[  0.21586932749148033E+005],]
input.temp=[[  0.21821368567276312E+003],]
input.temp_p1=[[  0.21936063505553668E+003],]
input.temp_m1=[[  0.21749059924129344E+003],]
input.tropLev=[[        37],]
input.tropP=[[  0.23595333341721096E+005],]
# Output data is stored here.
output = Object()
output.tropopause_interpolateT=[[  0.21838214914457546E+003],]
