# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          30 , time step=        1403 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.pmid=[[  0.23329055374482632E+005],]
input.pmid_p1=[[  0.25217854115082242E+005],]
input.pmid_m1=[[  0.21588204331068970E+005],]
input.temp=[[  0.21810495330306492E+003],]
input.temp_p1=[[  0.21923320804521265E+003],]
input.temp_m1=[[  0.21738616225203305E+003],]
input.tropLev=[[        37],]
input.tropP=[[  0.23657617481883681E+005],]
# Output data is stored here.
output = Object()
output.tropopause_interpolateT=[[  0.21830763458985851E+003],]
