# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          30 , time step=        1413 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.pmid=[[  0.23341543301571568E+005],]
input.pint=[[  0.22433438703849471E+005],]
input.pint_p1=[[  0.24249647899293665E+005],]
input.zm=[[  0.98278017332717045E+004],]
input.zi=[[  0.10075472214711224E+005],]
input.zi_p1=[[  0.95801312518321829E+004],]
input.tropP=[[  0.23170659336158518E+005],]
# Output data is stored here.
output = Object()
output.tropopause_interpolateZ=[[  0.98736629880611526E+004],]
