# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          30 , time step=        1410 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.pmid=[[  0.23346325172374269E+005],]
input.pint=[[  0.22437378234277130E+005],]
input.pint_p1=[[  0.24255272110471407E+005],]
input.zm=[[  0.98352901337242929E+004],]
input.zi=[[  0.10083282871853977E+005],]
input.zi_p1=[[  0.95872973955946109E+004],]
input.tropP=[[  0.23275363957331690E+005],]
# Output data is stored here.
output = Object()
output.tropopause_interpolateZ=[[  0.98543003762983535E+004],]
