# Data at [lat=  -13.2292708024991      , lon=   139.817062054960      , k=           0 , time step=         355 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.prefri=[[         7],]
input.ncol=[[         4],]
input.ref_ind=[[  0.14927671566442187E+001,  0.14977990581258016E+001,  0.14979918561451162E+001,  0.14733067874363983E+001,],]
input.ref_table=[[  0.13669091463088989E+001,  0.14640909632047017E+001,  0.15612727801005046E+001,  0.16584545969963074E+001,  0.17556364138921101E+001,  0.18528182307879129E+001,  0.19500000476837158E+001,],]
# Output data is stored here.
output = Object()
output.ix=[[         2,         2,         2,         2,],]
output.tt=[[  0.29507776614490777E+000,  0.34685598600447354E+000,  0.34883987584593751E+000,  0.94830746389293466E-001,],]
