#ifdef YAML_INTI_DRYDEP

        !open I/O yaml files
        !(with an optional argument to pass a unique string to differentiate file names)
        call open_files('drydep_inti_xactive', &  !intent-in
!             unit_input, unit_output, trim(ext_str)) !intent-out, with the use of ext_str
             unit_input, unit_output) !intent-out

    !write some meta data
        write(meta_msg,*)'# Data at initialization'
        subr_name='find_season_index'

    !write header for the input file
        write(unit_input,'(A)')adjustl(trim(meta_msg))
        write(unit_input,'(A)')'mam4xx:'
        write(unit_input,'(A,A)')'  function: ',trim(adjustl(subr_name))
        write(unit_input,'(A)')'input:'
        write(unit_input,'(A)' )'  fixed:'

    !write header for the output file
        write(unit_output,'(A)')adjustl(trim(meta_msg))
        write(unit_output,'(A)')'# This file was generated by E3SM.'
        write(unit_output,'(A)')
        write(unit_output,'(A)')'from math import nan as nan, inf as inf'
        write(unit_output,'(A)')

        write(unit_output,'(A)')'# Object is just a dynamic container that stores input/output data.'
        write(unit_output,'(A)')'class Object(object):'
        write(unit_output,'(A)')'    pass'

        write(unit_output,'(A)')'# Settings are stored here.'
        write(unit_output,'(A)')'settings = Object()'
        write(unit_output,'(A)')'# Input is stored here.'
        write(unit_output,'(A)')'input = Object()'


        ! add code for writing data here
        
        call write_var(unit_input,unit_output,'clat',clat(:))
        call write_var(unit_input,unit_output,'wk_lai',wk_lai(:,:,:))
        call write_var(unit_input,unit_output,'lat_lai',lat_lai(:))

        !writes aerosol mmr from state%q or q vector (cloud borne and interstitial)
        !"aer_num_only" is .ture. if printing aerosol num only
        !call write_aerosol_mmr_from_stateq(unit_input, unit_output, fld_name,field,aer_num_only)

        !close only the input file, not the output file
        close(unit_input)
        call freeunit(unit_input)

#endif
