# Data at [lat=  -5.57727434969463      , lon=   184.674947489650      , k=          55 , time step=         379 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.qgcm_intrst=[[  0.54795406035641909E+010],]
input.qgcm_cldbrn=[[  0.00000000000000000E+000],]
input.fcldy=[[  0.63094534408394366E-002],]
input.fclea=[[  0.99369054655916056E+000],]
# Output data is stored here.
output = Object()
output.factor_clea=[[  0.10000000000000000E+001],]
output.factor_cldy=[[  0.10000000000000007E+001],]
