# Data at [lat=  -13.2292708024991      , lon=   139.817062054960      , k=          51 , time step=         355 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.ncol=[[         4],]
input.dgncur_a=[[ 0.1330978176E-06, 0.4132278142E-07, 0.1394631584E-05, 0.1000000012E-06,],]
input.state_q=[[ 0.6818013995E-02, 0.6161223535E-19, 0.0000000000E+00, 0.1000000000E-11,],]
# Output data is stored here.
output = Object()
output.hygro=[[ 0.2052752129E+00, 0.1944073080E+00, 0.5890183536E+00, 0.6149771289E-07,],]
output.naer=[[ 0.2264456039E+09, 0.5281324971E+09, 0.2867674196E+05, 0.1665751220E+07,],]
output.dryrad=[[ 0.1117402402E-06, 0.2877830753E-07, 0.1170841648E-05, 0.6964271883E-07,],]
output.dryvol=[[ 0.5844096935E-20, 0.9983535284E-22, 0.6723309375E-17, 0.1414867471E-20,],]
output.drymass=[[ 0.6775249809E-17, 0.1112290319E-18, 0.1010841977E-13, 0.1533519601E-17,],]
output.rhcrystal=[[ 0.3500000000E+00, 0.3500000000E+00, 0.3500000000E+00, 0.3500000000E+00,],]
output.rhdeliques=[[ 0.8000000000E+00, 0.8000000000E+00, 0.8000000000E+00, 0.8000000000E+00,],]
output.specdens_1=[[ 0.1770000000E+04, 0.1770000000E+04, 0.2600000000E+04, 0.1000000000E+04,],]
