# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1404 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.ncol=[[         4],]
input.temp=[[0.2530858554E+003],]
input.rate=[[-.9876543200E+008,-.9876543200E+008,-.9876543200E+008,-.9876543200E+008,-.9876543200E+008,-.9876543200E+008,-.9876543200E+008,],]
input.pver=[[        72],]
input.pcols=[[         4],]
input.rxntot=[[         7],]
# Output data is stored here.
output = Object()
output.rate=[[-.9876543200E+008,-.9876543200E+008,0.1541127368E-011,-.9876543200E+008,0.3808272488E-011,-.9876543200E+008,0.1482763417E-011,],]
