# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1409 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.ncol=[[         4],]
input.temp=[[0.2516766072E+003],]
input.rate=[[              NaN,              NaN,              NaN,              NaN,              NaN,              NaN,              NaN,],]
input.pver=[[        72],]
input.pcols=[[         4],]
input.rxntot=[[         7],]
# Output data is stored here.
output = Object()
output.rate=[[              NaN,              NaN,0.1535681503E-011,              NaN,0.3788607353E-011,              NaN,0.1499920863E-011,],]
