# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          30 , time step=        1413 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.ncol=[[         4],]
input.lchnk=[[       137],]
input.o3col=[[  0.66920034946321070E+019],]
input.temp=[[  0.21491395921262099E+003],]
input.sza=[[  0.10415247701075736E+001],]
input.pmid=[[  0.13368217993210610E+005],]
input.delta_t=[[  0.36000000000000000E+004],]
input.rlats=[[  0.68518123468168590E+000],]
input.ltrop=[[        35],]
input.linoz_o3_clim=[[  0.48796443716473551E-006],]
input.linoz_t_clim=[[  0.21560790362322260E+003],]
input.linoz_o3col_clim=[[  0.28128339718612182E+003],]
input.linoz_PmL_clim=[[ -0.43205754455344996E-015],]
input.linoz_dPmL_dO3=[[ -0.10759259754533287E-007],]
input.linoz_dPmL_dT=[[ -0.10509373968893823E-015],]
input.linoz_dPmL_dO3col=[[ -0.62399085695150869E-017],]
input.linoz_cariolle_psc=[[  0.28506880653600129E-007],]
input.o3_vmr=[[  0.45015885739617291E-006],]
input.pcols=[[         4],]
input.pver=[[        72],]
input.chlorine_loading=[[  0.32864836736409750E+001],]
input.do_lin_stratchem=[[         1],]
input.radians_to_degrees=[[  0.57295779513082323E+002],]
input.chlorine_loading_bgnd=[[  0.00000000000000000E+000],]
# Output data is stored here.
output = Object()
output.o3_vmr=[[  0.45015975290837635E-006],]
