# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          30 , time step=        1401 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.ncol=[[         4],]
input.lchnk=[[       137],]
input.o3col=[[  0.65506582830258043E+019],]
input.temp=[[  0.21396448912056178E+003],]
input.sza=[[  0.23239805382489460E+001],]
input.pmid=[[  0.13368217993210610E+005],]
input.delta_t=[[  0.36000000000000000E+004],]
input.rlats=[[  0.68518123468168590E+000],]
input.ltrop=[[        35],]
input.linoz_o3_clim=[[  0.48743804442717537E-006],]
input.linoz_t_clim=[[  0.21561811683608300E+003],]
input.linoz_o3col_clim=[[  0.28121523782050571E+003],]
input.linoz_PmL_clim=[[ -0.43671889839468485E-015],]
input.linoz_dPmL_dO3=[[ -0.10733540283126868E-007],]
input.linoz_dPmL_dT=[[ -0.10490414172947188E-015],]
input.linoz_dPmL_dO3col=[[ -0.61822888418064245E-017],]
input.linoz_cariolle_psc=[[  0.28506880653600129E-007],]
input.o3_vmr=[[  0.36754011905336104E-006],]
input.pcols=[[         4],]
input.pver=[[        72],]
input.chlorine_loading=[[  0.32864836736409750E+001],]
input.do_lin_stratchem=[[         1],]
input.radians_to_degrees=[[  0.57295779513082323E+002],]
input.chlorine_loading_bgnd=[[  0.00000000000000000E+000],]
# Output data is stored here.
output = Object()
output.o3_vmr=[[  0.36754463715151265E-006],]
