# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          30 , time step=        1403 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.ncol=[[         4],]
input.lchnk=[[       137],]
input.o3col=[[  0.65820723689416438E+019],]
input.temp=[[  0.21406275419250366E+003],]
input.sza=[[  0.19408210412260345E+001],]
input.pmid=[[  0.13368217993210610E+005],]
input.delta_t=[[  0.36000000000000000E+004],]
input.rlats=[[  0.68518123468168590E+000],]
input.ltrop=[[        35],]
input.linoz_o3_clim=[[  0.48752577655014282E-006],]
input.linoz_t_clim=[[  0.21561641463393880E+003],]
input.linoz_o3col_clim=[[  0.28122659771478033E+003],]
input.linoz_PmL_clim=[[ -0.43594200608745065E-015],]
input.linoz_dPmL_dO3=[[ -0.10737826861696600E-007],]
input.linoz_dPmL_dT=[[ -0.10493574138939765E-015],]
input.linoz_dPmL_dO3col=[[ -0.61918921297623405E-017],]
input.linoz_cariolle_psc=[[  0.28506880653600129E-007],]
input.o3_vmr=[[  0.38129814848194222E-006],]
input.pcols=[[         4],]
input.pver=[[        72],]
input.chlorine_loading=[[  0.32864836736409750E+001],]
input.do_lin_stratchem=[[         1],]
input.radians_to_degrees=[[  0.57295779513082323E+002],]
input.chlorine_loading_bgnd=[[  0.00000000000000000E+000],]
input.psc_T=[[  0.19750000000000000E+003],]
# Output data is stored here.
output = Object()
output.o3_vmr=[[  0.38130208070716375E-006],]
output.do3_linoz=[[  0.10922847837628872E-014],]
output.do3_linoz_psc=[[  0.00000000000000000E+000],]
output.ss_o3=[[  0.48302319115073780E-006],]
output.o3col_du_diag=[[  0.24495989463869159E+003],]
output.o3clim_linoz_diag=[[  0.48752577655014282E-006],]
