# Data at [lat=   40.1837635770142      , lon=   223.838476568273      , k=          22 , time step=         592 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.ncol=[[         4],]
input.lchnk=[[       164],]
input.o3col=[[  0.49610014980541041E+019],]
input.temp=[[  0.19719223592910672E+003],]
input.sza=[[  0.15962666601004716E+001],]
input.pmid=[[  0.68476390229712551E+004],]
input.delta_t=[[  0.36000000000000000E+004],]
input.rlats=[[  0.70497830836867026E+000],]
input.ltrop=[[        26],]
input.linoz_o3_clim=[[  0.17266727819509029E-005],]
input.linoz_t_clim=[[  0.21372100216112401E+003],]
input.linoz_o3col_clim=[[  0.22887132220696594E+003],]
input.linoz_PmL_clim=[[ -0.15261313493457146E-013],]
input.linoz_dPmL_dO3=[[ -0.15111737596197867E-007],]
input.linoz_dPmL_dT=[[ -0.70336032673425370E-015],]
input.linoz_dPmL_dO3col=[[  0.12977963031111365E-016],]
input.linoz_cariolle_psc=[[  0.98939133830725435E-006],]
input.o3_vmr=[[  0.68087799833613521E-006],]
input.pcols=[[         4],]
input.pver=[[        72],]
input.chlorine_loading=[[  0.32864836736409750E+001],]
input.do_lin_stratchem=[[         1],]
input.radians_to_degrees=[[  0.57295779513082323E+002],]
input.chlorine_loading_bgnd=[[  0.00000000000000000E+000],]
input.psc_T=[[  0.19750000000000000E+003],]
# Output data is stored here.
output = Object()
output.o3_vmr=[[  0.67700731632672316E-006],]
output.do3_linoz=[[  0.11593660477251978E-013],]
output.do3_linoz_psc=[[ -0.10751894470589031E-011],]
output.ss_o3=[[  0.14480945918571816E-005],]
output.o3col_du_diag=[[  0.18462975430048766E+003],]
output.o3clim_linoz_diag=[[  0.17266727819509029E-005],]
