# Data at [lat=   40.1837635770142      , lon=   223.838476568273      , k=          22 , time step=         588 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.ncol=[[         4],]
input.lchnk=[[       164],]
input.o3col=[[  0.49894167091712102E+019],]
input.temp=[[  0.19729769585956060E+003],]
input.sza=[[  0.23761259232884879E+001],]
input.pmid=[[  0.68476390229712551E+004],]
input.delta_t=[[  0.36000000000000000E+004],]
input.rlats=[[  0.70497830836867026E+000],]
input.ltrop=[[        25],]
input.linoz_o3_clim=[[  0.17259808090529586E-005],]
input.linoz_t_clim=[[  0.21371881113113881E+003],]
input.linoz_o3col_clim=[[  0.22882790663297340E+003],]
input.linoz_PmL_clim=[[ -0.15241188092552049E-013],]
input.linoz_dPmL_dO3=[[ -0.15089410319359031E-007],]
input.linoz_dPmL_dT=[[ -0.70224244360861138E-015],]
input.linoz_dPmL_dO3col=[[  0.13075782419188397E-016],]
input.linoz_cariolle_psc=[[  0.98939133830725435E-006],]
input.o3_vmr=[[  0.72802436885613224E-006],]
input.pcols=[[         4],]
input.pver=[[        72],]
input.chlorine_loading=[[  0.32864836736409750E+001],]
input.do_lin_stratchem=[[         1],]
input.radians_to_degrees=[[  0.57295779513082323E+002],]
input.chlorine_loading_bgnd=[[  0.00000000000000000E+000],]
input.psc_T=[[  0.19750000000000000E+003],]
# Output data is stored here.
output = Object()
output.o3_vmr=[[  0.72806319341474361E-006],]
output.do3_linoz=[[  0.10784599614267131E-013],]
output.do3_linoz_psc=[[  0.00000000000000000E+000],]
output.ss_o3=[[  0.14427569070076695E-005],]
output.o3col_du_diag=[[  0.18568726122706400E+003],]
output.o3clim_linoz_diag=[[  0.17259808090529586E-005],]
