# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1407 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.ncol=[[         4],]
input.inv=[[0.2120364965E+020,0.1675088322E+020,0.4452766427E+019,0.3078968068E+017,0.8864482496E+006,0.5992449566E+008,0.8338073716E+008,0.1165927896E+013,],]
input.mtot=[[0.2120364965E+020],]
input.rate=[[-.9876543200E+008,0.4843548521E-011,0.1537526922E-011,0.9918093910E-012,0.3795267593E-011,0.1170799837E-010,0.1494077843E-011,],]
input.pver=[[        72],]
input.nfs=[[         8],]
input.rxntot=[[         7],]
# Output data is stored here.
output = Object()
output.rate=[[-.9876543200E+008,0.1588124317E-014,0.1362938048E-005,0.8791876986E-006,0.3364308314E-005,0.1037853466E-004,0.8953186123E-004,],]
