# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1412 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.ncol=[[         4],]
input.inv=[[0.2122366383E+020,0.1676669442E+020,0.4456969403E+019,0.3207254228E+017,0.8908428396E+006,0.5987796532E+008,0.8370002635E+008,0.1167699914E+013,],]
input.mtot=[[0.2122366383E+020],]
input.rate=[[              NaN,0.4919072052E-011,0.1536226092E-011,0.9930887990E-012,0.3790572425E-011,0.1175515447E-010,0.1498193467E-011,],]
input.pver=[[        72],]
input.nfs=[[         8],]
input.rxntot=[[         7],]
# Output data is stored here.
output = Object()
output.rate=[[              NaN,0.1623730750E-014,0.1368536014E-005,0.8846860457E-006,0.3376804303E-005,0.1047199519E-004,0.8970877645E-004,],]
