# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1415 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.ncol=[[         4],]
input.inv=[[0.2125555514E+020,0.1679188856E+020,0.4463666579E+019,0.3115790638E+017,0.8942930399E+006,0.6006278355E+008,0.8396403282E+008,0.1169633931E+013,],]
input.mtot=[[0.2125555514E+020],]
input.rate=[[-.9876543200E+008,0.4918372075E-011,0.1535115540E-011,0.9943448404E-012,0.3786565494E-011,0.1179525041E-010,0.1501718819E-011,],]
input.pver=[[        72],]
input.nfs=[[         8],]
input.rxntot=[[         7],]
# Output data is stored here.
output = Object()
output.rate=[[-.9876543200E+008,0.1631306277E-014,0.1372843142E-005,0.8892356700E-006,0.3386299167E-005,0.1054841034E-004,0.9019741240E-004,],]
