# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1410 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.ncol=[[         4],]
input.inv=[[0.2123339516E+020,0.1677438218E+020,0.4459012984E+019,0.3230191386E+017,0.8898050094E+006,0.6007892567E+008,0.8363677553E+008,0.1167777497E+013,],]
input.mtot=[[0.2123339516E+020],]
input.rate=[[-.9876543200E+008,0.4923152125E-011,0.1536423353E-011,0.9930389092E-012,0.3791284296E-011,0.1174842524E-010,0.1497568408E-011,],]
input.pver=[[        72],]
input.nfs=[[         8],]
input.rxntot=[[         7],]
# Output data is stored here.
output = Object()
output.rate=[[-.9876543200E+008,0.1621878719E-014,0.1367117196E-005,0.8836109959E-006,0.3373503759E-005,0.1045380763E-004,0.8997230108E-004,],]
