# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1403 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.ncol=[[         4],]
input.inv=[[0.2104726381E+020,0.1662733841E+020,0.4419925401E+019,0.3523531524E+017,0.8772097816E+006,0.5889917620E+008,0.8260209496E+008,0.1157749464E+013,],]
input.mtot=[[0.2104726381E+020],]
input.rate=[[              NaN,0.4850387980E-011,0.1542544645E-011,0.9859356762E-012,0.3813395585E-011,0.1151608010E-010,0.1478340352E-011,],]
input.pver=[[        72],]
input.nfs=[[         8],]
input.rxntot=[[         7],]
# Output data is stored here.
output = Object()
output.rate=[[              NaN,0.1572399722E-014,0.1353135251E-005,0.8648724192E-006,0.3345147908E-005,0.1010201811E-004,0.8707302885E-004,],]
