# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1416 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.ncol=[[         4],]
input.inv=[[0.2128790704E+020,0.1681744657E+020,0.4470460479E+019,0.3019533133E+017,0.8963350002E+006,0.6033823529E+008,0.8413187211E+008,0.1171256666E+013,],]
input.mtot=[[0.2128790704E+020],]
input.rate=[[              NaN,0.4908205787E-011,0.1534314250E-011,0.9953536327E-012,0.3783675232E-011,0.1182409839E-010,0.1504269183E-011,],]
input.pver=[[        72],]
input.nfs=[[         8],]
input.rxntot=[[         7],]
# Output data is stored here.
output = Object()
output.rate=[[              NaN,0.1631965239E-014,0.1375259564E-005,0.8921702986E-006,0.3391440540E-005,0.1059835323E-004,0.9076494792E-004,],]
