# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1402 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.ncol=[[         4],]
input.inv=[[0.2100766128E+020,0.1659605241E+020,0.4411608868E+019,0.3674342396E+017,0.8748747591E+006,0.5870698813E+008,0.8240324243E+008,0.1155584327E+013,],]
input.mtot=[[0.2100766128E+020],]
input.rate=[[-.9876543200E+008,0.4855865213E-011,0.1544070174E-011,0.9842269160E-012,0.3818912418E-011,0.1145544186E-010,0.1473598712E-011,],]
input.pver=[[        72],]
input.nfs=[[         8],]
input.rxntot=[[         7],]
# Output data is stored here.
output = Object()
output.rate=[[-.9876543200E+008,0.1569558541E-014,0.1350868022E-005,0.8610752860E-006,0.3341070082E-005,0.1002207694E-004,0.8651054212E-004,],]
