# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1408 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.ncol=[[         4],]
input.inv=[[0.2124050005E+020,0.1677999504E+020,0.4460505010E+019,0.3097017922E+017,0.8886740452E+006,0.6016205564E+008,0.8356754708E+008,0.1167868128E+013,],]
input.mtot=[[0.2124050005E+020],]
input.rate=[[              NaN,0.4881621368E-011,0.1536330041E-011,0.9931944193E-012,0.3790947550E-011,0.1175195198E-010,0.1497864042E-011,],]
input.pver=[[        72],]
input.nfs=[[         8],]
input.rxntot=[[         7],]
# Output data is stored here.
output = Object()
output.rate=[[              NaN,0.1604998622E-014,0.1365296633E-005,0.8826261022E-006,0.3368916694E-005,0.1044365471E-004,0.9011457981E-004,],]
