# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1405 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.ncol=[[         4],]
input.inv=[[0.2112860059E+020,0.1669159447E+020,0.4437006125E+019,0.3258407042E+017,0.8819565369E+006,0.5940600631E+008,0.8300398007E+008,0.1162031521E+013,],]
input.mtot=[[0.2112860059E+020],]
input.rate=[[-.9876543200E+008,0.4839770884E-011,0.1539835354E-011,0.9890810111E-012,0.3803604085E-011,0.1162116970E-010,0.1486810649E-011,],]
input.pver=[[        72],]
input.nfs=[[         8],]
input.rxntot=[[         7],]
# Output data is stored here.
output = Object()
output.rate=[[-.9876543200E+008,0.1578163170E-014,0.1358067856E-005,0.8723264632E-006,0.3354613486E-005,0.1024936658E-004,0.8832548280E-004,],]
