# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1406 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.ncol=[[         4],]
input.inv=[[0.2116988459E+020,0.1672420883E+020,0.4445675765E+019,0.3151040713E+017,0.8843590485E+006,0.5966938383E+008,0.8320730518E+008,0.1164195445E+013,],]
input.mtot=[[0.2116988459E+020],]
input.rate=[[-.9876543200E+008,0.4841185749E-011,0.1538483776E-011,0.9906502959E-012,0.3798722399E-011,0.1167224022E-010,0.1491059939E-011,],]
input.pver=[[        72],]
input.nfs=[[         8],]
input.rxntot=[[         7],]
# Output data is stored here.
output = Object()
output.rate=[[-.9876543200E+008,0.1583274325E-014,0.1360572048E-005,0.8760905532E-006,0.3359434527E-005,0.1032245126E-004,0.8897062780E-004,],]
