# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1409 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.ncol=[[         4],]
input.inv=[[0.2125723353E+020,0.1679321449E+020,0.4464019041E+019,0.3226931191E+017,0.8900780598E+006,0.6024157369E+008,0.8367944681E+008,0.1168847288E+013,],]
input.mtot=[[0.2125723353E+020],]
input.rate=[[-.9876543200E+008,0.4942648134E-011,0.1535681503E-011,0.9939068189E-012,0.3788607353E-011,0.1177540007E-010,0.1499920863E-011,],]
input.pver=[[        72],]
input.nfs=[[         8],]
input.rxntot=[[         7],]
# Output data is stored here.
output = Object()
output.rate=[[-.9876543200E+008,0.1628135522E-014,0.1366876413E-005,0.8846546530E-006,0.3372156282E-005,0.1048102525E-004,0.9035759318E-004,],]
