# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1414 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.ncol=[[         4],]
input.inv=[[0.2124754129E+020,0.1678555762E+020,0.4461983672E+019,0.3163262766E+017,0.8932618441E+006,0.5994937597E+008,0.8388869252E+008,0.1169217634E+013,],]
input.mtot=[[0.2124754129E+020],]
input.rate=[[              NaN,0.4932865694E-011,0.1535145110E-011,0.9942309315E-012,0.3786672170E-011,0.1179398728E-010,0.1501624809E-011,],]
input.pver=[[        72],]
input.nfs=[[         8],]
input.rxntot=[[         7],]
# Output data is stored here.
output = Object()
output.rate=[[              NaN,0.1633794615E-014,0.1371286552E-005,0.8881085554E-006,0.3382489766E-005,0.1053511882E-004,0.9002147022E-004,],]
