# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1413 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.ncol=[[         4],]
input.inv=[[0.2123656277E+020,0.1677688459E+020,0.4459678181E+019,0.3191839617E+017,0.8920943087E+006,0.5990411627E+008,0.8379861604E+008,0.1168529069E+013,],]
input.mtot=[[0.2123656277E+020],]
input.rate=[[-.9876543200E+008,0.4930470686E-011,0.1535595679E-011,0.9937436573E-012,0.3788297698E-011,0.1177783401E-010,0.1500193328E-011,],]
input.pver=[[        72],]
input.nfs=[[         8],]
input.rxntot=[[         7],]
# Output data is stored here.
output = Object()
output.rate=[[-.9876543200E+008,0.1630338738E-014,0.1369896166E-005,0.8865130610E-006,0.3379518816E-005,0.1050693869E-004,0.8986775558E-004,],]
