# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1404 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.ncol=[[         4],]
input.inv=[[0.2108813192E+020,0.1665962422E+020,0.4428507703E+019,0.3391925919E+017,0.8795924591E+006,0.5913898706E+008,0.8280430145E+008,0.1159921508E+013,],]
input.mtot=[[0.2108813192E+020],]
input.rate=[[              NaN,0.4847360726E-011,0.1541127368E-011,0.9875644472E-012,0.3808272488E-011,0.1157146676E-010,0.1482763417E-011,],]
input.pver=[[        72],]
input.nfs=[[         8],]
input.rxntot=[[         7],]
# Output data is stored here.
output = Object()
output.rate=[[              NaN,0.1576061012E-014,0.1355564011E-005,0.8686542406E-006,0.3349727762E-005,0.1017817490E-004,0.8768912655E-004,],]
