# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1401 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.ncol=[[         4],]
input.inv=[[0.2097263536E+020,0.1656838193E+020,0.4404253425E+019,0.3844547901E+017,0.8727138092E+006,0.5862955476E+008,0.8221832968E+008,0.1153525055E+013,],]
input.mtot=[[0.2097263536E+020],]
input.rate=[[              NaN,0.4862284536E-011,0.1545769581E-011,0.9824217596E-012,0.3825061020E-011,0.1138676334E-010,0.1468340018E-011,],]
input.pver=[[        72],]
input.nfs=[[         8],]
input.rxntot=[[         7],]
# Output data is stored here.
output = Object()
output.rate=[[              NaN,0.1567200866E-014,0.1349014459E-005,0.8573730361E-006,0.3338183573E-005,0.9937385611E-005,0.8608812148E-004,],]
