# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1411 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.ncol=[[         4],]
input.inv=[[0.2122310716E+020,0.1676625466E+020,0.4456852503E+019,0.3223956293E+017,0.8900959173E+006,0.5996857646E+008,0.8364682557E+008,0.1167432709E+013,],]
input.mtot=[[0.2122310716E+020],]
input.rate=[[-.9876543200E+008,0.4915789897E-011,0.1536594412E-011,0.9927845211E-012,0.3791901640E-011,0.1174202838E-010,0.1497026656E-011,],]
input.pver=[[        72],]
input.nfs=[[         8],]
input.rxntot=[[         7],]
# Output data is stored here.
output = Object()
output.rate=[[-.9876543200E+008,0.1620627760E-014,0.1367716412E-005,0.8836734490E-006,0.3375156168E-005,0.1045153152E-004,0.8977455748E-004,],]
