# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1416 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.w_in=[[0.2660863725E+000],]
input.wmaxf=[[0.1000000000E+002],]
input.tair=[[0.2512437090E+003],]
input.rhoair=[[0.1024260068E+001],]
input.na=[[0.1209778137E+009,0.2337402891E+010,0.5021075343E+005,0.7166087807E+008,],]
input.nmode=[[         4],]
input.volume=[[0.4661017862E-012,0.7813094065E-013,0.2140374654E-012,0.1013906453E-012,],]
input.hygro=[[0.4039892109E+000,0.4475923891E+000,0.1104300108E+001,0.8962006572E-007,],]
input.rair=[[0.2870423114E+003],]
input.latvap=[[0.2501000000E+007],]
input.rh2o=[[0.4615046398E+003],]
input.gravit=[[0.9806160000E+001],]
input.cpair=[[0.1004640000E+004],]
input.rhoh2o=[[0.1000000000E+004],]
input.pi=[[0.3141592654E+001],]
input.alogsig=[[0.5877866649E+000,0.4700036292E+000,0.5877866649E+000,0.4700036441E+000,],]
input.exp45logsig=[[0.4733757267E+001,0.2702197556E+001,0.4733757267E+001,0.2702197727E+001,],]
input.t0=[[0.2730000000E+003],]
input.aten=[[0.1206437615E-008],]
input.twothird=[[0.6666666667E+000],]
input.sq2=[[0.1414213562E+001],]
# Output data is stored here.
output = Object()
output.fn=[[0.6969879460E+000,0.1217800015E-001,0.9999997912E+000,0.0000000000E+000,],]
output.fm=[[0.9886699455E+000,0.2000463441E+000,0.1000000000E+001,0.0000000000E+000,],]
output.fluxn=[[0.1854589942E+000,0.3240399885E-002,0.2660863169E+000,0.0000000000E+000,],]
output.fluxm=[[0.2630715994E+000,0.5322960603E-001,0.2660863725E+000,0.0000000000E+000,],]
output.flux_fullact=[[0.2660863725E+000],]
