# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1404 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.w_in=[[ 0.2626360556E+00],]
input.wmaxf=[[ 0.1000000000E+02],]
input.tair=[[ 0.2530799514E+03],]
input.rhoair=[[ 0.1014345531E+01],]
input.na=[[ 0.1059123459E+09, 0.1891020485E+10, 0.7100269228E+05, 0.6906038658E+08,],]
input.nmode=[[         4],]
input.volume=[[ 0.5109433858E-12, 0.7911720427E-13, 0.2864044891E-12, 0.9771129450E-13,],]
input.hygro=[[ 0.4137402143E+00, 0.4552801476E+00, 0.1121990243E+01, 0.1146984343E-06,],]
input.rair=[[ 0.2870423114E+03],]
input.latvap=[[ 0.2501000000E+07],]
input.rh2o=[[ 0.4615046398E+03],]
input.gravit=[[ 0.9806160000E+01],]
input.cpair=[[ 0.1004640000E+04],]
input.rhoh2o=[[ 0.1000000000E+04],]
input.pi=[[ 0.3141592654E+01],]
input.alogsig=[[ 0.5877866649E+00, 0.4700036292E+00, 0.5877866649E+00, 0.4700036441E+00,],]
input.exp45logsig=[[ 0.4733757267E+01, 0.2702197556E+01, 0.4733757267E+01, 0.2702197727E+01,],]
input.t0=[[ 0.2730000000E+03],]
input.aten=[[ 0.1206437615E-08],]
input.twothird=[[ 0.6666666667E+00],]
input.sq2=[[ 0.1414213562E+01],]
# Output data is stored here.
output = Object()
output.fn=[[ 0.7271526216E+00, 0.1593897195E-01, 0.9999996916E+00, 0.0000000000E+00,],]
output.fm=[[ 0.9910476712E+00, 0.2308875982E+00, 0.1000000000E+01, 0.0000000000E+00,],]
output.fluxn=[[ 0.1909764964E+00, 0.4186148724E-02, 0.2626359746E+00, 0.0000000000E+00,],]
output.fluxm=[[ 0.2602848513E+00, 0.6063940809E-01, 0.2626360556E+00, 0.0000000000E+00,],]
output.flux_fullact=[[ 0.2626360556E+00],]
