# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1410 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.w_in=[[0.4063044805E+000],]
input.wmaxf=[[0.1000000000E+002],]
input.tair=[[0.2515033414E+003],]
input.rhoair=[[0.1022789508E+001],]
input.na=[[0.9751929906E+008,0.2036340026E+010,0.4337157317E+005,0.7378206270E+008,],]
input.nmode=[[         4],]
input.volume=[[0.3722026284E-012,0.6993109349E-013,0.1901938234E-012,0.1043918404E-012,],]
input.hygro=[[0.4072215679E+000,0.4394863719E+000,0.1108495088E+001,0.8682254547E-007,],]
input.rair=[[0.2870423114E+003],]
input.latvap=[[0.2501000000E+007],]
input.rh2o=[[0.4615046398E+003],]
input.gravit=[[0.9806160000E+001],]
input.cpair=[[0.1004640000E+004],]
input.rhoh2o=[[0.1000000000E+004],]
input.pi=[[0.3141592654E+001],]
input.alogsig=[[0.5877866649E+000,0.4700036292E+000,0.5877866649E+000,0.4700036441E+000,],]
input.exp45logsig=[[0.4733757267E+001,0.2702197556E+001,0.4733757267E+001,0.2702197727E+001,],]
input.t0=[[0.2730000000E+003],]
input.aten=[[0.1206437615E-008],]
input.twothird=[[0.6666666667E+000],]
input.sq2=[[0.1414213562E+001],]
# Output data is stored here.
output = Object()
output.fn=[[0.7776425752E+000,0.2658863141E-001,0.9999999504E+000,0.0000000000E+000,],]
output.fm=[[0.9942580018E+000,0.3003243958E+000,0.1000000000E+001,0.0000000000E+000,],]
output.fluxn=[[0.3159596625E+000,0.1080308007E-001,0.4063044604E+000,0.0000000000E+000,],]
output.fluxm=[[0.4039714809E+000,0.1220231476E+000,0.4063044805E+000,0.0000000000E+000,],]
output.flux_fullact=[[0.4063044805E+000],]
