# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1401 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.w_in=[[0.2035884056E+000],]
input.wmaxf=[[0.1000000000E+002],]
input.tair=[[0.2542867631E+003],]
input.rhoair=[[0.1008801927E+001],]
input.na=[[0.8937784261E+008,0.1907348618E+010,0.5376344290E+005,0.6882922125E+008,],]
input.nmode=[[         4],]
input.volume=[[0.3946815160E-012,0.7711726592E-013,0.2179731889E-012,0.9738422619E-013,],]
input.hygro=[[0.4182897233E+000,0.4604913313E+000,0.1123981733E+001,0.1186599978E-006,],]
input.rair=[[0.2870423114E+003],]
input.latvap=[[0.2501000000E+007],]
input.rh2o=[[0.4615046398E+003],]
input.gravit=[[0.9806160000E+001],]
input.cpair=[[0.1004640000E+004],]
input.rhoh2o=[[0.1000000000E+004],]
input.pi=[[0.3141592654E+001],]
input.alogsig=[[0.5877866649E+000,0.4700036292E+000,0.5877866649E+000,0.4700036441E+000,],]
input.exp45logsig=[[0.4733757267E+001,0.2702197556E+001,0.4733757267E+001,0.2702197727E+001,],]
input.t0=[[0.2730000000E+003],]
input.aten=[[0.1206437615E-008],]
input.twothird=[[0.6666666667E+000],]
input.sq2=[[0.1414213562E+001],]
# Output data is stored here.
output = Object()
output.fn=[[0.6748900728E+000,0.1084641082E-001,0.9999994774E+000,0.0000000000E+000,],]
output.fm=[[0.9866821928E+000,0.1878915077E+000,0.1000000000E+001,0.0000000000E+000,],]
output.fluxn=[[0.1373997938E+000,0.2208203484E-002,0.2035882992E+000,0.0000000000E+000,],]
output.fluxm=[[0.2008770544E+000,0.3825253248E-001,0.2035884055E+000,0.0000000000E+000,],]
output.flux_fullact=[[0.2035884056E+000],]
