# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1402 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.w_in=[[0.2556753903E+000],]
input.wmaxf=[[0.1000000000E+002],]
input.tair=[[0.2538687326E+003],]
input.rhoair=[[0.1010384180E+001],]
input.na=[[0.1072368571E+009,0.1947725316E+010,0.6431589171E+005,0.7107454087E+008,],]
input.nmode=[[         4],]
input.volume=[[0.5104232535E-012,0.8167891329E-013,0.2627826205E-012,0.1005610559E-012,],]
input.hygro=[[0.4190711761E+000,0.4581741794E+000,0.1118467193E+001,0.1129317356E-006,],]
input.rair=[[0.2870423114E+003],]
input.latvap=[[0.2501000000E+007],]
input.rh2o=[[0.4615046398E+003],]
input.gravit=[[0.9806160000E+001],]
input.cpair=[[0.1004640000E+004],]
input.rhoh2o=[[0.1000000000E+004],]
input.pi=[[0.3141592654E+001],]
input.alogsig=[[0.5877866649E+000,0.4700036292E+000,0.5877866649E+000,0.4700036441E+000,],]
input.exp45logsig=[[0.4733757267E+001,0.2702197556E+001,0.4733757267E+001,0.2702197727E+001,],]
input.t0=[[0.2730000000E+003],]
input.aten=[[0.1206437615E-008],]
input.twothird=[[0.6666666667E+000],]
input.sq2=[[0.1414213562E+001],]
# Output data is stored here.
output = Object()
output.fn=[[0.7145839069E+000,0.1440373781E-001,0.9999996371E+000,0.0000000000E+000,],]
output.fm=[[0.9901018470E+000,0.2188448991E+000,0.1000000000E+001,0.0000000000E+000,],]
output.fluxn=[[0.1827015193E+000,0.3682681286E-002,0.2556752975E+000,0.0000000000E+000,],]
output.fluxm=[[0.2531446762E+000,0.5595325501E-001,0.2556753903E+000,0.0000000000E+000,],]
output.flux_fullact=[[0.2556753903E+000],]
