# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1410 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.w_in=[[ 0.3945409021E+00],]
input.wmaxf=[[ 0.1000000000E+02],]
input.tair=[[ 0.2515421904E+03],]
input.rhoair=[[ 0.1022631545E+01],]
input.na=[[ 0.1066813363E+09, 0.1872802610E+10, 0.5876640142E+05, 0.6762145016E+08,],]
input.nmode=[[         4],]
input.volume=[[ 0.4669974282E-12, 0.7428793558E-13, 0.2451867481E-12, 0.9567539015E-13,],]
input.hygro=[[ 0.4047241976E+00, 0.4394474984E+00, 0.1113647048E+01, 0.1003926732E-06,],]
input.rair=[[ 0.2870423114E+03],]
input.latvap=[[ 0.2501000000E+07],]
input.rh2o=[[ 0.4615046398E+03],]
input.gravit=[[ 0.9806160000E+01],]
input.cpair=[[ 0.1004640000E+04],]
input.rhoh2o=[[ 0.1000000000E+04],]
input.pi=[[ 0.3141592654E+01],]
input.alogsig=[[ 0.5877866649E+00, 0.4700036292E+00, 0.5877866649E+00, 0.4700036441E+00,],]
input.exp45logsig=[[ 0.4733757267E+01, 0.2702197556E+01, 0.4733757267E+01, 0.2702197727E+01,],]
input.t0=[[ 0.2730000000E+03],]
input.aten=[[ 0.1206437615E-08],]
input.twothird=[[ 0.6666666667E+00],]
input.sq2=[[ 0.1414213562E+01],]
# Output data is stored here.
output = Object()
output.fn=[[ 0.7851500170E+00, 0.2922287322E-01, 0.9999999255E+00, 0.0000000000E+00,],]
output.fm=[[ 0.9946610243E+00, 0.3147862228E+00, 0.1000000000E+01, 0.0000000000E+00,],]
output.fluxn=[[ 0.3097737960E+00, 0.1152961876E-01, 0.3945408727E+00, 0.0000000000E+00,],]
output.fluxm=[[ 0.3924344578E+00, 0.1241960403E+00, 0.3945409021E+00, 0.0000000000E+00,],]
output.flux_fullact=[[ 0.3945409021E+00],]
