# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1403 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.w_in=[[0.2643378056E+000],]
input.wmaxf=[[0.1000000000E+002],]
input.tair=[[0.2534582809E+003],]
input.rhoair=[[0.1012340558E+001],]
input.na=[[0.1074162332E+009,0.1920210065E+010,0.6866138119E+005,0.7020946243E+008,],]
input.nmode=[[         4],]
input.volume=[[0.5203981188E-012,0.8049363264E-013,0.2775947101E-012,0.9933708454E-013,],]
input.hygro=[[0.4162435263E+000,0.4572300019E+000,0.1119873699E+001,0.1135870944E-006,],]
input.rair=[[0.2870423114E+003],]
input.latvap=[[0.2501000000E+007],]
input.rh2o=[[0.4615046398E+003],]
input.gravit=[[0.9806160000E+001],]
input.cpair=[[0.1004640000E+004],]
input.rhoh2o=[[0.1000000000E+004],]
input.pi=[[0.3141592654E+001],]
input.alogsig=[[0.5877866649E+000,0.4700036292E+000,0.5877866649E+000,0.4700036441E+000,],]
input.exp45logsig=[[0.4733757267E+001,0.2702197556E+001,0.4733757267E+001,0.2702197727E+001,],]
input.t0=[[0.2730000000E+003],]
input.aten=[[0.1206437615E-008],]
input.twothird=[[0.6666666667E+000],]
input.sq2=[[0.1414213562E+001],]
# Output data is stored here.
output = Object()
output.fn=[[0.7252600185E+000,0.1554458948E-001,0.9999996731E+000,0.0000000000E+000,],]
output.fm=[[0.9909092165E+000,0.2278583231E+000,0.1000000000E+001,0.0000000000E+000,],]
output.fluxn=[[0.1917136418E+000,0.4109022671E-002,0.2643377192E+000,0.0000000000E+000,],]
output.fluxm=[[0.2619347678E+000,0.6023156910E-001,0.2643378056E+000,0.0000000000E+000,],]
output.flux_fullact=[[0.2643378056E+000],]
