# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1406 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.w_in=[[ 0.2241076667E+00],]
input.wmaxf=[[ 0.1000000000E+02],]
input.tair=[[ 0.2524349778E+03],]
input.rhoair=[[ 0.1018114707E+01],]
input.na=[[ 0.1137132687E+09, 0.1834291608E+10, 0.7846701859E+05, 0.6693479873E+08,],]
input.nmode=[[         4],]
input.volume=[[ 0.5562548706E-12, 0.7956185752E-13, 0.3109841459E-12, 0.9470386938E-13,],]
input.hygro=[[ 0.4045796589E+00, 0.4391958268E+00, 0.1121687452E+01, 0.1144597052E-06,],]
input.rair=[[ 0.2870423114E+03],]
input.latvap=[[ 0.2501000000E+07],]
input.rh2o=[[ 0.4615046398E+03],]
input.gravit=[[ 0.9806160000E+01],]
input.cpair=[[ 0.1004640000E+04],]
input.rhoh2o=[[ 0.1000000000E+04],]
input.pi=[[ 0.3141592654E+01],]
input.alogsig=[[ 0.5877866649E+00, 0.4700036292E+00, 0.5877866649E+00, 0.4700036441E+00,],]
input.exp45logsig=[[ 0.4733757267E+01, 0.2702197556E+01, 0.4733757267E+01, 0.2702197727E+01,],]
input.t0=[[ 0.2730000000E+03],]
input.aten=[[ 0.1206437615E-08],]
input.twothird=[[ 0.6666666667E+00],]
input.sq2=[[ 0.1414213562E+01],]
# Output data is stored here.
output = Object()
output.fn=[[ 0.7001145562E+00, 0.1256936788E-01, 0.9999995234E+00, 0.0000000000E+00,],]
output.fm=[[ 0.9889338601E+00, 0.2034805634E+00, 0.1000000000E+01, 0.0000000000E+00,],]
output.fluxn=[[ 0.1569010396E+00, 0.2816891709E-02, 0.2241075599E+00, 0.0000000000E+00,],]
output.fluxm=[[ 0.2216276600E+00, 0.4560155430E-01, 0.2241076667E+00, 0.0000000000E+00,],]
output.flux_fullact=[[ 0.2241076667E+00],]
