# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1404 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.w_in=[[0.2152003824E+000],]
input.wmaxf=[[0.1000000000E+002],]
input.tair=[[0.2530823261E+003],]
input.rhoair=[[0.1014336013E+001],]
input.na=[[0.9677985115E+008,0.1831719502E+010,0.6864879677E+005,0.6655352366E+008,],]
input.nmode=[[         4],]
input.volume=[[0.4661696543E-012,0.7489352691E-013,0.2739334723E-012,0.9416441569E-013,],]
input.hygro=[[0.4086758444E+000,0.4541606919E+000,0.1124254174E+001,0.1196490158E-006,],]
input.rair=[[0.2870423114E+003],]
input.latvap=[[0.2501000000E+007],]
input.rh2o=[[0.4615046398E+003],]
input.gravit=[[0.9806160000E+001],]
input.cpair=[[0.1004640000E+004],]
input.rhoh2o=[[0.1000000000E+004],]
input.pi=[[0.3141592654E+001],]
input.alogsig=[[0.5877866649E+000,0.4700036292E+000,0.5877866649E+000,0.4700036441E+000,],]
input.exp45logsig=[[0.4733757267E+001,0.2702197556E+001,0.4733757267E+001,0.2702197727E+001,],]
input.t0=[[0.2730000000E+003],]
input.aten=[[0.1206437615E-008],]
input.twothird=[[0.6666666667E+000],]
input.sq2=[[0.1414213562E+001],]
# Output data is stored here.
output = Object()
output.fn=[[0.7001306890E+000,0.1211288688E-001,0.9999995430E+000,0.0000000000E+000,],]
output.fm=[[0.9889352110E+000,0.1994691900E+000,0.1000000000E+001,0.0000000000E+000,],]
output.fluxn=[[0.1506683920E+000,0.2606697887E-002,0.2152002840E+000,0.0000000000E+000,],]
output.fluxm=[[0.2128192356E+000,0.4292584597E-001,0.2152003824E+000,0.0000000000E+000,],]
output.flux_fullact=[[0.2152003824E+000],]
