# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1403 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.w_in=[[ 0.2643378056E+00],]
input.wmaxf=[[ 0.1000000000E+02],]
input.tair=[[ 0.2534582809E+03],]
input.rhoair=[[ 0.1012340558E+01],]
input.na=[[ 0.1074162332E+09, 0.1920210065E+10, 0.6866138119E+05, 0.7020946243E+08,],]
input.nmode=[[         4],]
input.volume=[[ 0.5203981188E-12, 0.8049363264E-13, 0.2775947101E-12, 0.9933708454E-13,],]
input.hygro=[[ 0.4162435263E+00, 0.4572300019E+00, 0.1119873699E+01, 0.1135870944E-06,],]
input.rair=[[ 0.2870423114E+03],]
input.latvap=[[ 0.2501000000E+07],]
input.rh2o=[[ 0.4615046398E+03],]
input.gravit=[[ 0.9806160000E+01],]
input.cpair=[[ 0.1004640000E+04],]
input.rhoh2o=[[ 0.1000000000E+04],]
input.pi=[[ 0.3141592654E+01],]
input.alogsig=[[ 0.5877866649E+00, 0.4700036292E+00, 0.5877866649E+00, 0.4700036441E+00,],]
input.exp45logsig=[[ 0.4733757267E+01, 0.2702197556E+01, 0.4733757267E+01, 0.2702197727E+01,],]
input.t0=[[ 0.2730000000E+03],]
input.aten=[[ 0.1206437615E-08],]
input.twothird=[[ 0.6666666667E+00],]
input.sq2=[[ 0.1414213562E+01],]
# Output data is stored here.
output = Object()
output.fn=[[ 0.7252600185E+00, 0.1554458948E-01, 0.9999996731E+00, 0.0000000000E+00,],]
output.fm=[[ 0.9909092165E+00, 0.2278583231E+00, 0.1000000000E+01, 0.0000000000E+00,],]
output.fluxn=[[ 0.1917136418E+00, 0.4109022671E-02, 0.2643377192E+00, 0.0000000000E+00,],]
output.fluxm=[[ 0.2619347678E+00, 0.6023156910E-01, 0.2643378056E+00, 0.0000000000E+00,],]
output.flux_fullact=[[ 0.2643378056E+00],]
