# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1406 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.w_in=[[0.2241076667E+000],]
input.wmaxf=[[0.1000000000E+002],]
input.tair=[[0.2524349778E+003],]
input.rhoair=[[0.1018114707E+001],]
input.na=[[0.1137132687E+009,0.1834291608E+010,0.7846701859E+005,0.6693479873E+008,],]
input.nmode=[[         4],]
input.volume=[[0.5562548706E-012,0.7956185752E-013,0.3109841459E-012,0.9470386938E-013,],]
input.hygro=[[0.4045796589E+000,0.4391958268E+000,0.1121687452E+001,0.1144597052E-006,],]
input.rair=[[0.2870423114E+003],]
input.latvap=[[0.2501000000E+007],]
input.rh2o=[[0.4615046398E+003],]
input.gravit=[[0.9806160000E+001],]
input.cpair=[[0.1004640000E+004],]
input.rhoh2o=[[0.1000000000E+004],]
input.pi=[[0.3141592654E+001],]
input.alogsig=[[0.5877866649E+000,0.4700036292E+000,0.5877866649E+000,0.4700036441E+000,],]
input.exp45logsig=[[0.4733757267E+001,0.2702197556E+001,0.4733757267E+001,0.2702197727E+001,],]
input.t0=[[0.2730000000E+003],]
input.aten=[[0.1206437615E-008],]
input.twothird=[[0.6666666667E+000],]
input.sq2=[[0.1414213562E+001],]
# Output data is stored here.
output = Object()
output.fn=[[0.7001145562E+000,0.1256936788E-001,0.9999995234E+000,0.0000000000E+000,],]
output.fm=[[0.9889338601E+000,0.2034805634E+000,0.1000000000E+001,0.0000000000E+000,],]
output.fluxn=[[0.1569010396E+000,0.2816891709E-002,0.2241075599E+000,0.0000000000E+000,],]
output.fluxm=[[0.2216276600E+000,0.4560155430E-001,0.2241076667E+000,0.0000000000E+000,],]
output.flux_fullact=[[0.2241076667E+000],]
