# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1413 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.w_in=[[ 0.3291434353E+00],]
input.wmaxf=[[ 0.1000000000E+02],]
input.tair=[[ 0.2515269102E+03],]
input.rhoair=[[ 0.1021979352E+01],]
input.na=[[ 0.1057921884E+09, 0.2033034416E+10, 0.4587285865E+05, 0.6869413727E+08,],]
input.nmode=[[         4],]
input.volume=[[ 0.3580703351E-12, 0.6345582393E-13, 0.2032322118E-12, 0.9719310026E-13,],]
input.hygro=[[ 0.3998442794E+00, 0.4438777004E+00, 0.1114272830E+01, 0.9491894519E-07,],]
input.rair=[[ 0.2870423114E+03],]
input.latvap=[[ 0.2501000000E+07],]
input.rh2o=[[ 0.4615046398E+03],]
input.gravit=[[ 0.9806160000E+01],]
input.cpair=[[ 0.1004640000E+04],]
input.rhoh2o=[[ 0.1000000000E+04],]
input.pi=[[ 0.3141592654E+01],]
input.alogsig=[[ 0.5877866649E+00, 0.4700036292E+00, 0.5877866649E+00, 0.4700036441E+00,],]
input.exp45logsig=[[ 0.4733757267E+01, 0.2702197556E+01, 0.4733757267E+01, 0.2702197727E+01,],]
input.t0=[[ 0.2730000000E+03],]
input.aten=[[ 0.1206437615E-08],]
input.twothird=[[ 0.6666666667E+00],]
input.sq2=[[ 0.1414213562E+01],]
# Output data is stored here.
output = Object()
output.fn=[[ 0.7222919256E+00, 0.1724209133E-01, 0.9999999201E+00, 0.0000000000E+00,],]
output.fm=[[ 0.9906892758E+00, 0.2406064224E+00, 0.1000000000E+01, 0.0000000000E+00,],]
output.fluxn=[[ 0.2377376457E+00, 0.5675121174E-02, 0.3291434090E+00, 0.0000000000E+00,],]
output.fluxm=[[ 0.3260788716E+00, 0.7919402443E-01, 0.3291434353E+00, 0.0000000000E+00,],]
output.flux_fullact=[[ 0.3291434353E+00],]
