# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1401 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.w_in=[[0.2340340085E+000],]
input.wmaxf=[[0.1000000000E+002],]
input.tair=[[0.2542998689E+003],]
input.rhoair=[[0.1008749936E+001],]
input.na=[[0.1001597027E+009,0.1976261666E+010,0.5628143596E+005,0.7193041474E+008,],]
input.nmode=[[         4],]
input.volume=[[0.4505666449E-012,0.8042799153E-013,0.2332356151E-012,0.1017720040E-012,],]
input.hygro=[[0.4211891837E+000,0.4606938169E+000,0.1120796260E+001,0.1131229966E-006,],]
input.rair=[[0.2870423114E+003],]
input.latvap=[[0.2501000000E+007],]
input.rh2o=[[0.4615046398E+003],]
input.gravit=[[0.9806160000E+001],]
input.cpair=[[0.1004640000E+004],]
input.rhoh2o=[[0.1000000000E+004],]
input.pi=[[0.3141592654E+001],]
input.alogsig=[[0.5877866649E+000,0.4700036292E+000,0.5877866649E+000,0.4700036441E+000,],]
input.exp45logsig=[[0.4733757267E+001,0.2702197556E+001,0.4733757267E+001,0.2702197727E+001,],]
input.t0=[[0.2730000000E+003],]
input.aten=[[0.1206437615E-008],]
input.twothird=[[0.6666666667E+000],]
input.sq2=[[0.1414213562E+001],]
# Output data is stored here.
output = Object()
output.fn=[[0.6934383600E+000,0.1243035936E-001,0.9999995920E+000,0.0000000000E+000,],]
output.fm=[[0.9883652356E+000,0.2022675269E+000,0.1000000000E+001,0.0000000000E+000,],]
output.fluxn=[[0.1622881590E+000,0.2909126829E-002,0.2340339130E+000,0.0000000000E+000,],]
output.fluxm=[[0.2313110779E+000,0.4733748010E-001,0.2340340085E+000,0.0000000000E+000,],]
output.flux_fullact=[[0.2340340085E+000],]
