# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1415 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.w_in=[[0.2861932349E+000],]
input.wmaxf=[[0.1000000000E+002],]
input.tair=[[0.2513147524E+003],]
input.rhoair=[[0.1023253552E+001],]
input.na=[[0.1043674946E+009,0.2506984377E+010,0.3139015175E+005,0.7733549810E+008,],]
input.nmode=[[         4],]
input.volume=[[0.3195123362E-012,0.7447940998E-013,0.1433231690E-012,0.1094194806E-012,],]
input.hygro=[[0.4055447766E+000,0.4513651612E+000,0.1099963986E+001,0.7436904777E-007,],]
input.rair=[[0.2870423114E+003],]
input.latvap=[[0.2501000000E+007],]
input.rh2o=[[0.4615046398E+003],]
input.gravit=[[0.9806160000E+001],]
input.cpair=[[0.1004640000E+004],]
input.rhoh2o=[[0.1000000000E+004],]
input.pi=[[0.3141592654E+001],]
input.alogsig=[[0.5877866649E+000,0.4700036292E+000,0.5877866649E+000,0.4700036441E+000,],]
input.exp45logsig=[[0.4733757267E+001,0.2702197556E+001,0.4733757267E+001,0.2702197727E+001,],]
input.t0=[[0.2730000000E+003],]
input.aten=[[0.1206437615E-008],]
input.twothird=[[0.6666666667E+000],]
input.sq2=[[0.1414213562E+001],]
# Output data is stored here.
output = Object()
output.fn=[[0.6825704096E+000,0.1321299593E-001,0.9999998919E+000,0.0000000000E+000,],]
output.fm=[[0.9873979049E+000,0.2090037977E+000,0.1000000000E+001,0.0000000000E+000,],]
output.fluxn=[[0.1953470336E+000,0.3781470046E-002,0.2861932039E+000,0.0000000000E+000,],]
output.fluxm=[[0.2825866005E+000,0.5981547295E-001,0.2861932349E+000,0.0000000000E+000,],]
output.flux_fullact=[[0.2861932349E+000],]
