# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1410 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.w_in=[[0.3945409021E+000],]
input.wmaxf=[[0.1000000000E+002],]
input.tair=[[0.2515421904E+003],]
input.rhoair=[[0.1022631545E+001],]
input.na=[[0.1066813363E+009,0.1872802610E+010,0.5876640142E+005,0.6762145016E+008,],]
input.nmode=[[         4],]
input.volume=[[0.4669974282E-012,0.7428793558E-013,0.2451867481E-012,0.9567539015E-013,],]
input.hygro=[[0.4047241976E+000,0.4394474984E+000,0.1113647048E+001,0.1003926732E-006,],]
input.rair=[[0.2870423114E+003],]
input.latvap=[[0.2501000000E+007],]
input.rh2o=[[0.4615046398E+003],]
input.gravit=[[0.9806160000E+001],]
input.cpair=[[0.1004640000E+004],]
input.rhoh2o=[[0.1000000000E+004],]
input.pi=[[0.3141592654E+001],]
input.alogsig=[[0.5877866649E+000,0.4700036292E+000,0.5877866649E+000,0.4700036441E+000,],]
input.exp45logsig=[[0.4733757267E+001,0.2702197556E+001,0.4733757267E+001,0.2702197727E+001,],]
input.t0=[[0.2730000000E+003],]
input.aten=[[0.1206437615E-008],]
input.twothird=[[0.6666666667E+000],]
input.sq2=[[0.1414213562E+001],]
# Output data is stored here.
output = Object()
output.fn=[[0.7851500170E+000,0.2922287322E-001,0.9999999255E+000,0.0000000000E+000,],]
output.fm=[[0.9946610243E+000,0.3147862228E+000,0.1000000000E+001,0.0000000000E+000,],]
output.fluxn=[[0.3097737960E+000,0.1152961876E-001,0.3945408727E+000,0.0000000000E+000,],]
output.fluxm=[[0.3924344578E+000,0.1241960403E+000,0.3945409021E+000,0.0000000000E+000,],]
output.flux_fullact=[[0.3945409021E+000],]
