# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1415 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.w_in=[[ 0.2861932349E+00],]
input.wmaxf=[[ 0.1000000000E+02],]
input.tair=[[ 0.2513147524E+03],]
input.rhoair=[[ 0.1023253552E+01],]
input.na=[[ 0.1043674946E+09, 0.2506984377E+10, 0.3139015175E+05, 0.7733549810E+08,],]
input.nmode=[[         4],]
input.volume=[[ 0.3195123362E-12, 0.7447940998E-13, 0.1433231690E-12, 0.1094194806E-12,],]
input.hygro=[[ 0.4055447766E+00, 0.4513651612E+00, 0.1099963986E+01, 0.7436904777E-07,],]
input.rair=[[ 0.2870423114E+03],]
input.latvap=[[ 0.2501000000E+07],]
input.rh2o=[[ 0.4615046398E+03],]
input.gravit=[[ 0.9806160000E+01],]
input.cpair=[[ 0.1004640000E+04],]
input.rhoh2o=[[ 0.1000000000E+04],]
input.pi=[[ 0.3141592654E+01],]
input.alogsig=[[ 0.5877866649E+00, 0.4700036292E+00, 0.5877866649E+00, 0.4700036441E+00,],]
input.exp45logsig=[[ 0.4733757267E+01, 0.2702197556E+01, 0.4733757267E+01, 0.2702197727E+01,],]
input.t0=[[ 0.2730000000E+03],]
input.aten=[[ 0.1206437615E-08],]
input.twothird=[[ 0.6666666667E+00],]
input.sq2=[[ 0.1414213562E+01],]
# Output data is stored here.
output = Object()
output.fn=[[ 0.6825704096E+00, 0.1321299593E-01, 0.9999998919E+00, 0.0000000000E+00,],]
output.fm=[[ 0.9873979049E+00, 0.2090037977E+00, 0.1000000000E+01, 0.0000000000E+00,],]
output.fluxn=[[ 0.1953470336E+00, 0.3781470046E-02, 0.2861932039E+00, 0.0000000000E+00,],]
output.fluxm=[[ 0.2825866005E+00, 0.5981547295E-01, 0.2861932349E+00, 0.0000000000E+00,],]
output.flux_fullact=[[ 0.2861932349E+00],]
