# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1412 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.w_in=[[ 0.3393839534E+00],]
input.wmaxf=[[ 0.1000000000E+02],]
input.tair=[[ 0.2516091114E+03],]
input.rhoair=[[ 0.1021684499E+01],]
input.na=[[ 0.1046792448E+09, 0.1945093341E+10, 0.4794873394E+05, 0.6793586210E+08,],]
input.nmode=[[         4],]
input.volume=[[ 0.3748779132E-12, 0.6377425776E-13, 0.2001686433E-12, 0.9612024139E-13,],]
input.hygro=[[ 0.4006672852E+00, 0.4415816410E+00, 0.1114483262E+01, 0.9810050335E-07,],]
input.rair=[[ 0.2870423114E+03],]
input.latvap=[[ 0.2501000000E+07],]
input.rh2o=[[ 0.4615046398E+03],]
input.gravit=[[ 0.9806160000E+01],]
input.cpair=[[ 0.1004640000E+04],]
input.rhoh2o=[[ 0.1000000000E+04],]
input.pi=[[ 0.3141592654E+01],]
input.alogsig=[[ 0.5877866649E+00, 0.4700036292E+00, 0.5877866649E+00, 0.4700036441E+00,],]
input.exp45logsig=[[ 0.4733757267E+01, 0.2702197556E+01, 0.4733757267E+01, 0.2702197727E+01,],]
input.t0=[[ 0.2730000000E+03],]
input.aten=[[ 0.1206437615E-08],]
input.twothird=[[ 0.6666666667E+00],]
input.sq2=[[ 0.1414213562E+01],]
# Output data is stored here.
output = Object()
output.fn=[[ 0.7364119009E+00, 0.1916664081E-01, 0.9999999090E+00, 0.0000000000E+00,],]
output.fm=[[ 0.9917052720E+00, 0.2542220851E+00, 0.1000000000E+01, 0.0000000000E+00,],]
output.fluxn=[[ 0.2499263822E+00, 0.6504850331E-02, 0.3393839225E+00, 0.0000000000E+00,],]
output.fluxm=[[ 0.3365688558E+00, 0.8627889628E-01, 0.3393839534E+00, 0.0000000000E+00,],]
output.flux_fullact=[[ 0.3393839534E+00],]
