# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1412 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.w_in=[[0.3393839534E+000],]
input.wmaxf=[[0.1000000000E+002],]
input.tair=[[0.2516091114E+003],]
input.rhoair=[[0.1021684499E+001],]
input.na=[[0.1046792448E+009,0.1945093341E+010,0.4794873394E+005,0.6793586210E+008,],]
input.nmode=[[         4],]
input.volume=[[0.3748779132E-012,0.6377425776E-013,0.2001686433E-012,0.9612024139E-013,],]
input.hygro=[[0.4006672852E+000,0.4415816410E+000,0.1114483262E+001,0.9810050335E-007,],]
input.rair=[[0.2870423114E+003],]
input.latvap=[[0.2501000000E+007],]
input.rh2o=[[0.4615046398E+003],]
input.gravit=[[0.9806160000E+001],]
input.cpair=[[0.1004640000E+004],]
input.rhoh2o=[[0.1000000000E+004],]
input.pi=[[0.3141592654E+001],]
input.alogsig=[[0.5877866649E+000,0.4700036292E+000,0.5877866649E+000,0.4700036441E+000,],]
input.exp45logsig=[[0.4733757267E+001,0.2702197556E+001,0.4733757267E+001,0.2702197727E+001,],]
input.t0=[[0.2730000000E+003],]
input.aten=[[0.1206437615E-008],]
input.twothird=[[0.6666666667E+000],]
input.sq2=[[0.1414213562E+001],]
# Output data is stored here.
output = Object()
output.fn=[[0.7364119009E+000,0.1916664081E-001,0.9999999090E+000,0.0000000000E+000,],]
output.fm=[[0.9917052720E+000,0.2542220851E+000,0.1000000000E+001,0.0000000000E+000,],]
output.fluxn=[[0.2499263822E+000,0.6504850331E-002,0.3393839225E+000,0.0000000000E+000,],]
output.fluxm=[[0.3365688558E+000,0.8627889628E-001,0.3393839534E+000,0.0000000000E+000,],]
output.flux_fullact=[[0.3393839534E+000],]
