# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1416 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.w_in=[[ 0.2660863725E+00],]
input.wmaxf=[[ 0.1000000000E+02],]
input.tair=[[ 0.2512437090E+03],]
input.rhoair=[[ 0.1024260068E+01],]
input.na=[[ 0.1209778137E+09, 0.2337402891E+10, 0.5021075343E+05, 0.7166087807E+08,],]
input.nmode=[[         4],]
input.volume=[[ 0.4661017862E-12, 0.7813094065E-13, 0.2140374654E-12, 0.1013906453E-12,],]
input.hygro=[[ 0.4039892109E+00, 0.4475923891E+00, 0.1104300108E+01, 0.8962006572E-07,],]
input.rair=[[ 0.2870423114E+03],]
input.latvap=[[ 0.2501000000E+07],]
input.rh2o=[[ 0.4615046398E+03],]
input.gravit=[[ 0.9806160000E+01],]
input.cpair=[[ 0.1004640000E+04],]
input.rhoh2o=[[ 0.1000000000E+04],]
input.pi=[[ 0.3141592654E+01],]
input.alogsig=[[ 0.5877866649E+00, 0.4700036292E+00, 0.5877866649E+00, 0.4700036441E+00,],]
input.exp45logsig=[[ 0.4733757267E+01, 0.2702197556E+01, 0.4733757267E+01, 0.2702197727E+01,],]
input.t0=[[ 0.2730000000E+03],]
input.aten=[[ 0.1206437615E-08],]
input.twothird=[[ 0.6666666667E+00],]
input.sq2=[[ 0.1414213562E+01],]
# Output data is stored here.
output = Object()
output.fn=[[ 0.6969879460E+00, 0.1217800015E-01, 0.9999997912E+00, 0.0000000000E+00,],]
output.fm=[[ 0.9886699455E+00, 0.2000463441E+00, 0.1000000000E+01, 0.0000000000E+00,],]
output.fluxn=[[ 0.1854589942E+00, 0.3240399885E-02, 0.2660863169E+00, 0.0000000000E+00,],]
output.fluxm=[[ 0.2630715994E+00, 0.5322960603E-01, 0.2660863725E+00, 0.0000000000E+00,],]
output.flux_fullact=[[ 0.2660863725E+00],]
