# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1409 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.w_in=[[ 0.3726100783E+00],]
input.wmaxf=[[ 0.1000000000E+02],]
input.tair=[[ 0.2517205041E+03],]
input.rhoair=[[ 0.1022277213E+01],]
input.na=[[ 0.1085712730E+09, 0.1730462448E+10, 0.7348319010E+05, 0.6305081385E+08,],]
input.nmode=[[         4],]
input.volume=[[ 0.5205572522E-12, 0.7478524653E-13, 0.2945559017E-12, 0.8920854552E-13,],]
input.hygro=[[ 0.3989883144E+00, 0.4301771352E+00, 0.1120438246E+01, 0.1162256095E-06,],]
input.rair=[[ 0.2870423114E+03],]
input.latvap=[[ 0.2501000000E+07],]
input.rh2o=[[ 0.4615046398E+03],]
input.gravit=[[ 0.9806160000E+01],]
input.cpair=[[ 0.1004640000E+04],]
input.rhoh2o=[[ 0.1000000000E+04],]
input.pi=[[ 0.3141592654E+01],]
input.alogsig=[[ 0.5877866649E+00, 0.4700036292E+00, 0.5877866649E+00, 0.4700036441E+00,],]
input.exp45logsig=[[ 0.4733757267E+01, 0.2702197556E+01, 0.4733757267E+01, 0.2702197727E+01,],]
input.t0=[[ 0.2730000000E+03],]
input.aten=[[ 0.1206437615E-08],]
input.twothird=[[ 0.6666666667E+00],]
input.sq2=[[ 0.1414213562E+01],]
# Output data is stored here.
output = Object()
output.fn=[[ 0.7857598775E+00, 0.2881641547E-01, 0.9999998966E+00, 0.0000000000E+00,],]
output.fm=[[ 0.9946929731E+00, 0.3126086676E+00, 0.1000000000E+01, 0.0000000000E+00,],]
output.fluxn=[[ 0.2927820495E+00, 0.1073728683E-01, 0.3726100398E+00, 0.0000000000E+00,],]
output.fluxm=[[ 0.3706326266E+00, 0.1164811401E+00, 0.3726100783E+00, 0.0000000000E+00,],]
output.flux_fullact=[[ 0.3726100783E+00],]
