# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1410 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.zeta=[[0.3337616219E-005],]
input.eta=[[0.7004442010E-004,0.3989973262E-005,0.1271548395E+000,0.1105038759E-003,],]
input.nmode=[[         4],]
input.smc=[[0.1706318535E-002,0.1299695545E-001,0.3331923191E-004,0.4553018282E+001,],]
input.f1=[[0.1185999321E+001,0.8685860218E+000,0.1185999321E+001,0.8685860522E+000,],]
input.f2=[[0.1146946666E+001,0.1117500907E+001,0.1146946666E+001,0.1117500911E+001,],]
# Output data is stored here.
output = Object()
output.smax=[[0.3423301398E-002],]
