# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1417 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.zeta=[[0.2177444001E-005],]
input.eta=[[0.1352217848E-004,0.9253288350E-006,0.2501899075E-001,0.3011682757E-004,],]
input.nmode=[[         4],]
input.smc=[[0.1686676318E-002,0.1341060019E-001,0.3278386180E-004,0.4452536918E+001,],]
input.f1=[[0.1185999321E+001,0.8685860218E+000,0.1185999321E+001,0.8685860522E+000,],]
input.f2=[[0.1146946666E+001,0.1117500907E+001,0.1146946666E+001,0.1117500911E+001,],]
# Output data is stored here.
output = Object()
output.smax=[[0.2180179255E-002],]
