# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1408 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.zeta=[[0.2789188744E-005],]
input.eta=[[0.4169460620E-004,0.2606983948E-005,0.5802644622E-001,0.7147768290E-004,],]
input.nmode=[[         4],]
input.smc=[[0.1615159478E-002,0.1255292848E-001,0.3365269742E-004,0.4195831083E+001,],]
input.f1=[[0.1185999321E+001,0.8685860218E+000,0.1185999321E+001,0.8685860522E+000,],]
input.f2=[[0.1146946666E+001,0.1117500907E+001,0.1146946666E+001,0.1117500911E+001,],]
# Output data is stored here.
output = Object()
output.smax=[[0.2924843769E-002],]
