# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1406 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.zeta=[[0.2409433807E-005],]
input.eta=[[0.2655393603E-004,0.1646158576E-005,0.3848158012E-001,0.4511158500E-004,],]
input.nmode=[[         4],]
input.smc=[[0.1614430490E-002,0.1243256965E-001,0.3406365417E-004,0.4264067706E+001,],]
input.f1=[[0.1185999321E+001,0.8685860218E+000,0.1185999321E+001,0.8685860522E+000,],]
input.f2=[[0.1146946666E+001,0.1117500907E+001,0.1146946666E+001,0.1117500911E+001,],]
# Output data is stored here.
output = Object()
output.smax=[[0.2564147889E-002],]
