# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1404 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.zeta=[[0.2529403754E-005],]
input.eta=[[0.3468941853E-004,0.1942886248E-005,0.5174504764E-001,0.5320036386E-004,],]
input.nmode=[[         4],]
input.smc=[[0.1607591681E-002,0.1243316120E-001,0.3376025142E-004,0.4259627858E+001,],]
input.f1=[[0.1185999321E+001,0.8685860218E+000,0.1185999321E+001,0.8685860522E+000,],]
input.f2=[[0.1146946666E+001,0.1117500907E+001,0.1146946666E+001,0.1117500911E+001,],]
# Output data is stored here.
output = Object()
output.smax=[[0.2738661736E-002],]
