# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1405 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.zeta=[[0.2438912471E-005],]
input.eta=[[0.2850840036E-004,0.1731819712E-005,0.4256644699E-001,0.4761374308E-004,],]
input.nmode=[[         4],]
input.smc=[[0.1624510169E-002,0.1243022613E-001,0.3357373451E-004,0.4250801940E+001,],]
input.f1=[[0.1185999321E+001,0.8685860218E+000,0.1185999321E+001,0.8685860522E+000,],]
input.f2=[[0.1146946666E+001,0.1117500907E+001,0.1146946666E+001,0.1117500911E+001,],]
# Output data is stored here.
output = Object()
output.smax=[[0.2614750325E-002],]
