# Data at [lat=   39.0553303768561      , lon=   352.440165015397      , k=          37 , time step=        1404 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.modeptr_accum=[[         1],]
input.modeptr_aitken=[[         2],]
input.modeptr_coarse=[[         3],]
input.numptr_amode=[[        23,        28,        36,        40,],]
input.alnsg_amode=[[ 0.5877866649E+00, 0.4700036292E+00, 0.5877866649E+00, 0.4700036441E+00,],]
input.lptr_dust_a_amode=[[        20,-999888777,        29,-999888777,],]
input.lptr_nacl_a_amode=[[        21,        26,        30,-999888777,],]
input.lptr_so4_a_amode=[[        16,        24,        31,-999888777,],]
input.lptr_bc_a_amode=[[        19,-999888777,        32,        38,],]
input.lptr_pom_a_amode=[[        17,-999888777,        33,        37,],]
input.lptr_soa_a_amode=[[        18,        25,        34,-999888777,],]
input.lptr_mom_a_amode=[[        22,        27,        35,        39,],]
input.so4_sz_thresh_icenuc=[[ 0.8000000000E-07],]
input.mincld=[[ 0.1000000000E-03],]
input.nucleate_ice_subgrid=[[ 0.1200000000E+01],]
input.ncol=[[         4],]
input.lchnk=[[       137],]
input.temperature=[[ 0.2160054731E+03],]
input.state_q=[[ 0.5358551952E-04, 0.0000000000E+00, 0.7120661434E-07, 0.1000000000E-11, 0.1741268529E+04, 0.1955696397E-35, 0.4001799617E-07, 0.1000000000E-11, 0.6733069705E+02, 0.2481598003E-06, 0.3189858730E-10, 0.1278242821E-12, 0.6103334787E-11, 0.3286959794E-13, 0.2012488102E-12, 0.4655832298E-09, 0.2163261387E-09, 0.1001552296E-08, 0.3110368460E-10, 0.1137495554E-10, 0.4830967451E-10, 0.7120776735E-11, 0.1706675591E+09, 0.3438936835E-11, 0.1384926291E-10, 0.9124319767E-14, 0.1267984471E-14, 0.8075283978E+08, 0.3355188613E-10, 0.2392366450E-09, 0.7140888871E-11, 0.4600833561E-12, 0.3133189682E-11, 0.9886571818E-11, 0.2012124248E-12, 0.4944203727E+05, 0.2138529354E-10, 0.3277399375E-11, 0.4323308942E-16, 0.1641961968E+08,],]
input.pmid=[[ 0.2346378114E+05],]
input.rho=[[ 0.3784315403E+00],]
input.wsubi=[[ 0.2000000000E+00],]
input.ast=[[ 0.7120661434E+00],]
input.dgnum=[[ 0.1535284746E-06, 0.5157700473E-07, 0.1085711795E-05, 0.1000000012E-06,],]
# Output data is stored here.
output = Object()
output.naai=[[ 0.0000000000E+00],]
output.naai_hom=[[ 0.0000000000E+00],]
output.nihf=[[ 0.0000000000E+00],]
output.niimm=[[ 0.0000000000E+00],]
output.nidep=[[ 0.0000000000E+00],]
output.nimey=[[ 0.0000000000E+00],]
