# Data at [lat=   39.0553303768561      , lon=   352.440165015397      , k=          37 , time step=        1406 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.modeptr_accum=[[         1],]
input.modeptr_aitken=[[         2],]
input.modeptr_coarse=[[         3],]
input.numptr_amode=[[        23,        28,        36,        40,],]
input.alnsg_amode=[[ 0.5877866649E+00, 0.4700036292E+00, 0.5877866649E+00, 0.4700036441E+00,],]
input.lptr_dust_a_amode=[[        20,-999888777,        29,-999888777,],]
input.lptr_nacl_a_amode=[[        21,        26,        30,-999888777,],]
input.lptr_so4_a_amode=[[        16,        24,        31,-999888777,],]
input.lptr_bc_a_amode=[[        19,-999888777,        32,        38,],]
input.lptr_pom_a_amode=[[        17,-999888777,        33,        37,],]
input.lptr_soa_a_amode=[[        18,        25,        34,-999888777,],]
input.lptr_mom_a_amode=[[        22,        27,        35,        39,],]
input.so4_sz_thresh_icenuc=[[ 0.8000000000E-07],]
input.mincld=[[ 0.1000000000E-03],]
input.ncol=[[         4],]
input.lchnk=[[       137],]
input.temperature=[[ 0.2162291542E+03],]
input.state_q=[[ 0.5640225907E-04, 0.0000000000E+00, 0.3316474520E-07, 0.1000000000E-11, 0.6653378641E+03, 0.8824855477E-37, 0.2794080647E-07, 0.1000000000E-11, 0.4839537060E+02, 0.2437309700E-06, 0.3141816848E-10, 0.7455563181E-13, 0.5846735159E-11, 0.4532826351E-13, 0.1195270102E-12, 0.4582641910E-09, 0.2165943510E-09, 0.1004313892E-08, 0.3112204703E-10, 0.1130403847E-10, 0.4968333405E-10, 0.7297406409E-11, 0.1699875324E+09, 0.3373643823E-11, 0.1376530034E-10, 0.9793079067E-14, 0.1355706670E-14, 0.7885848960E+08, 0.3299128659E-10, 0.2465366391E-09, 0.7070463899E-11, 0.4470653077E-12, 0.3034930944E-11, 0.9690032381E-11, 0.2027867934E-12, 0.5093410939E+05, 0.2100893833E-10, 0.3213787599E-11, 0.4422679947E-16, 0.1612356649E+08,],]
input.pmid=[[ 0.2345738215E+05],]
input.rho=[[ 0.3779369685E+00],]
input.wsubi=[[ 0.2000000000E+00],]
input.ast=[[ 0.3316474520E+00],]
input.dgnum=[[ 0.1537122098E-06, 0.5183740215E-07, 0.1083050841E-05, 0.1000000012E-06,],]
# Output data is stored here.
output = Object()
output.naai=[[ 0.1396028040E+07],]
output.naai_hom=[[ 0.1396028040E+07],]
output.nihf=[[ 0.5276106053E+06],]
output.niimm=[[ 0.0000000000E+00],]
output.nidep=[[ 0.0000000000E+00],]
output.nimey=[[ 0.0000000000E+00],]
