# Data at [lat=   27.8859484222059      , lon=   83.8815732902265      , k=          44 , time step=        1410 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.modeptr_accum=[[         1],]
input.modeptr_aitken=[[         2],]
input.modeptr_coarse=[[         3],]
input.numptr_amode=[[        23,        28,        36,        40,],]
input.alnsg_amode=[[ 0.5877866649E+00, 0.4700036292E+00, 0.5877866649E+00, 0.4700036441E+00,],]
input.lptr_dust_a_amode=[[        20,-999888777,        29,-999888777,],]
input.lptr_nacl_a_amode=[[        21,        26,        30,-999888777,],]
input.lptr_so4_a_amode=[[        16,        24,        31,-999888777,],]
input.lptr_bc_a_amode=[[        19,-999888777,        32,        38,],]
input.lptr_pom_a_amode=[[        17,-999888777,        33,        37,],]
input.lptr_soa_a_amode=[[        18,        25,        34,-999888777,],]
input.lptr_mom_a_amode=[[        22,        27,        35,        39,],]
input.so4_sz_thresh_icenuc=[[ 0.8000000000E-07],]
input.mincld=[[ 0.1000000000E-03],]
input.ncol=[[         4],]
input.lchnk=[[       114],]
input.temperature=[[ 0.2373950401E+03],]
input.state_q=[[ 0.3477973440E-03, 0.7888609052E-30, 0.2774589740E-04, 0.1264794392E+06, 0.1079042573E+07, 0.4947354719E-13, 0.7405924404E-06, 0.2898065787E-02, 0.2617306180E+03, 0.1392340411E-06, 0.1765735847E-09, 0.5596693426E-13, 0.1126966307E-10, 0.9369351809E-13, 0.7312325862E-11, 0.1384232074E-08, 0.2138048213E-09, 0.9736906186E-09, 0.3830768034E-10, 0.1299407400E-10, 0.7834467259E-10, 0.1210422482E-10, 0.1983481446E+09, 0.1625256023E-10, 0.1586678953E-10, 0.3997451398E-13, 0.5885590259E-14, 0.2418643618E+09, 0.1991821069E-09, 0.4744548529E-09, 0.2505845180E-10, 0.1115722975E-11, 0.6402175108E-11, 0.1650528854E-10, 0.2947887252E-12, 0.1033559575E+06, 0.1086172984E-09, 0.2282653662E-10, 0.9755330896E-16, 0.8117440625E+08,],]
input.pmid=[[ 0.3691236844E+05],]
input.rho=[[ 0.5416944083E+00],]
input.wsubi=[[ 0.2000000000E+00],]
input.ast=[[ 0.9990000000E+00],]
input.dgnum=[[ 0.1614176541E-06, 0.4130500110E-07, 0.1133878851E-05, 0.1000000012E-06,],]
# Output data is stored here.
output = Object()
output.naai=[[ 0.2847341106E+05],]
output.naai_hom=[[ 0.0000000000E+00],]
output.nihf=[[ 0.0000000000E+00],]
output.niimm=[[ 0.1542388755E+05],]
output.nidep=[[ 0.0000000000E+00],]
output.nimey=[[ 0.0000000000E+00],]
