# Data at [lat=   39.0553303768561      , lon=   274.307569375767      , k=          72 , time step=        1417 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.ncol=[[         4],]
input.pver=[[        72],]
input.mwdry=[[  0.28966000000000001E+002],]
# Output data is stored here.
output = Object()
output.mbar=[[  0.28966000000000001E+002],]
