# Data at [lat=  -5.57727434969463      , lon=   184.674947489650      , k=           7 , time step=         379 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.accom=[[  0.65000000000000002E+000],]
input.gasdiffus=[[  0.59484156096949485E-002],]
input.gasfreepath=[[  0.93165938370073139E-004],]
input.beta_inp=[[  0.00000000000000000E+000],]
input.n_mode=[[         4],]
input.dgncur_awet=[[  0.53500000000000003E-007,  0.36090348505141279E-007,  0.18049318198666652E-005,  0.56402830042098117E-007,],]
input.lnsg=[[  0.58778666490211906E+000,  0.47000362924573563E+000,  0.58778666490211906E+000,  0.47000364414689666E+000,],]
# Output data is stored here.
output = Object()
output.uptkrate=[[  0.55848790840463725E-012,  0.19810629292320812E-012,  0.63297267475646403E-009,  0.48384117958218090E-012,],]
