# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1410 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.ncol=[[         4],]
input.temp=[[  0.25186794733003740E+003],]
input.invariants=[[  0.21233395162935738E+020,  0.16774382178719234E+020,  0.44590129842165048E+019,  0.32301913861969048E+017,  0.88980500937834207E+006,  0.60078925665359616E+008,  0.83636775527461961E+008,  0.11677774965517493E+013,],]
input.mtot=[[  0.21233395162935738E+020],]
input.rxt=[[ -0.98765432000000000E+008, -0.98765432000000000E+008,  0.15364233534047569E-011, -0.98765432000000000E+008,  0.37912842962957774E-011, -0.98765432000000000E+008,  0.14975684083606474E-011,],]
input.nfs=[[         8],]
input.rxntot=[[         7],]
input.inv_h2o_ndx=[[         4],]
input.t0=[[  0.30000000000000000E+003],]
input.usr_HO2_HO2_ndx=[[         2],]
input.usr_DMS_OH_ndx=[[         6],]
input.usr_SO2_OH_ndx=[[         4],]
# Output data is stored here.
output = Object()
output.rxt=[[ -0.98765432000000000E+008,  0.49231521247772328E-011,  0.15364233534047569E-011,  0.99303890921819824E-012,  0.37912842962957774E-011,  0.11748425240076376E-010,  0.14975684083606474E-011,],]
