# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1411 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.ncol=[[         4],]
input.temp=[[  0.25191209535514304E+003],]
input.invariants=[[  0.21223107158948061E+020,  0.16766254655568970E+020,  0.44568525033790925E+019,  0.32239562929016132E+017,  0.89009591728892364E+006,  0.59968576456229292E+008,  0.83646825569653511E+008,  0.11674327090402058E+013,],]
input.mtot=[[  0.21223107158948061E+020],]
input.rxt=[[ -0.98765432000000000E+008, -0.98765432000000000E+008,  0.15365944118085884E-011, -0.98765432000000000E+008,  0.37919016398576846E-011, -0.98765432000000000E+008,  0.14970266560086565E-011,],]
input.nfs=[[         8],]
input.rxntot=[[         7],]
input.inv_h2o_ndx=[[         4],]
input.t0=[[  0.30000000000000000E+003],]
input.usr_HO2_HO2_ndx=[[         2],]
input.usr_DMS_OH_ndx=[[         6],]
input.usr_SO2_OH_ndx=[[         4],]
# Output data is stored here.
output = Object()
output.rxt=[[ -0.98765432000000000E+008,  0.49157898974147992E-011,  0.15365944118085884E-011,  0.99278452106915344E-012,  0.37919016398576846E-011,  0.11742028375543991E-010,  0.14970266560086565E-011,],]
