# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1414 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.ncol=[[         4],]
input.temp=[[  0.25153838282546428E+003],]
input.invariants=[[  0.21247541292958527E+020,  0.16785557621437237E+020,  0.44619836715212908E+019,  0.31632627659996616E+017,  0.89326184413328453E+006,  0.59949375971999742E+008,  0.83888692521733344E+008,  0.11692176343223093E+013,],]
input.mtot=[[  0.21247541292958527E+020],]
input.rxt=[[ -0.98765432000000000E+008, -0.98765432000000000E+008,  0.15351451103992876E-011, -0.98765432000000000E+008,  0.37866721701492559E-011, -0.98765432000000000E+008,  0.15016248085227714E-011,],]
input.nfs=[[         8],]
input.rxntot=[[         7],]
input.inv_h2o_ndx=[[         4],]
input.t0=[[  0.30000000000000000E+003],]
input.usr_HO2_HO2_ndx=[[         2],]
input.usr_DMS_OH_ndx=[[         6],]
input.usr_SO2_OH_ndx=[[         4],]
# Output data is stored here.
output = Object()
output.rxt=[[ -0.98765432000000000E+008,  0.49328656935042186E-011,  0.15351451103992876E-011,  0.99423093152029684E-012,  0.37866721701492559E-011,  0.11793987275075562E-010,  0.15016248085227714E-011,],]
