# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1401 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.ncol=[[         4],]
input.temp=[[  0.25429567378100737E+003],]
input.invariants=[[  0.20972635356426965E+020,  0.16568381931577303E+020,  0.44042534248496625E+019,  0.38445479011570696E+017,  0.87271380922435306E+006,  0.58629554759878717E+008,  0.82218329680570617E+008,  0.11535250552045730E+013,],]
input.mtot=[[  0.20972635356426965E+020],]
input.rxt=[[ -0.98765432000000000E+008, -0.98765432000000000E+008,  0.15457695809876203E-011, -0.98765432000000000E+008,  0.38250610196185859E-011, -0.98765432000000000E+008,  0.14683400178130946E-011,],]
input.nfs=[[         8],]
input.rxntot=[[         7],]
input.inv_h2o_ndx=[[         4],]
input.t0=[[  0.30000000000000000E+003],]
input.usr_HO2_HO2_ndx=[[         2],]
input.usr_DMS_OH_ndx=[[         6],]
input.usr_SO2_OH_ndx=[[         4],]
# Output data is stored here.
output = Object()
output.rxt=[[ -0.98765432000000000E+008,  0.48622845364112009E-011,  0.15457695809876203E-011,  0.98242175956488407E-012,  0.38250610196185859E-011,  0.11386763341708891E-010,  0.14683400178130946E-011,],]
