# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1403 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.ncol=[[         4],]
input.temp=[[  0.25345437830920554E+003],]
input.invariants=[[  0.21047263813723836E+020,  0.16627338412841832E+020,  0.44199254008820055E+019,  0.35235315239289960E+017,  0.87720978160489909E+006,  0.58899176201589495E+008,  0.82602094959085107E+008,  0.11577494641958994E+013,],]
input.mtot=[[  0.21047263813723836E+020],]
input.rxt=[[ -0.98765432000000000E+008, -0.98765432000000000E+008,  0.15425446450432352E-011, -0.98765432000000000E+008,  0.38133955850649258E-011, -0.98765432000000000E+008,  0.14783403515138354E-011,],]
input.nfs=[[         8],]
input.rxntot=[[         7],]
input.inv_h2o_ndx=[[         4],]
input.t0=[[  0.30000000000000000E+003],]
input.usr_HO2_HO2_ndx=[[         2],]
input.usr_DMS_OH_ndx=[[         6],]
input.usr_SO2_OH_ndx=[[         4],]
# Output data is stored here.
output = Object()
output.rxt=[[ -0.98765432000000000E+008,  0.48503879803463259E-011,  0.15425446450432352E-011,  0.98593567617410721E-012,  0.38133955850649258E-011,  0.11516080097004763E-010,  0.14783403515138354E-011,],]
