# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1415 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.ncol=[[         4],]
input.temp=[[  0.25153076563850570E+003],]
input.invariants=[[  0.21255555140383134E+020,  0.16791888560902676E+020,  0.44636665794804577E+019,  0.31157906378414116E+017,  0.89429303992605954E+006,  0.60062783553320609E+008,  0.83964032821417570E+008,  0.11696339308249133E+013,],]
input.mtot=[[  0.21255555140383134E+020],]
input.rxt=[[ -0.98765432000000000E+008, -0.98765432000000000E+008,  0.15351155395041355E-011, -0.98765432000000000E+008,  0.37865654941583216E-011, -0.98765432000000000E+008,  0.15017188192929573E-011,],]
input.nfs=[[         8],]
input.rxntot=[[         7],]
input.inv_h2o_ndx=[[         4],]
input.t0=[[  0.30000000000000000E+003],]
input.usr_HO2_HO2_ndx=[[         2],]
input.usr_DMS_OH_ndx=[[         6],]
input.usr_SO2_OH_ndx=[[         4],]
# Output data is stored here.
output = Object()
output.rxt=[[ -0.98765432000000000E+008,  0.49183720750031211E-011,  0.15351155395041355E-011,  0.99434484036441897E-012,  0.37865654941583216E-011,  0.11795250408507367E-010,  0.15017188192929573E-011,],]
