# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1406 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.ncol=[[         4],]
input.temp=[[  0.25240041995122448E+003],]
input.invariants=[[  0.21169884592990450E+020,  0.16724208828462457E+020,  0.44456757645279944E+019,  0.31510407127245828E+017,  0.88435904854983534E+006,  0.59669383829351515E+008,  0.83207305175211579E+008,  0.11641954445773586E+013,],]
input.mtot=[[  0.21169884592990450E+020],]
input.rxt=[[ -0.98765432000000000E+008, -0.98765432000000000E+008,  0.15384837756565521E-011, -0.98765432000000000E+008,  0.37987223992923760E-011, -0.98765432000000000E+008,  0.14910599387870188E-011,],]
input.nfs=[[         8],]
input.rxntot=[[         7],]
input.inv_h2o_ndx=[[         4],]
input.t0=[[  0.30000000000000000E+003],]
input.usr_HO2_HO2_ndx=[[         2],]
input.usr_DMS_OH_ndx=[[         6],]
input.usr_SO2_OH_ndx=[[         4],]
# Output data is stored here.
output = Object()
output.rxt=[[ -0.98765432000000000E+008,  0.48411857486656129E-011,  0.15384837756565521E-011,  0.99065029593881945E-012,  0.37987223992923760E-011,  0.11672240223402638E-010,  0.14910599387870188E-011,],]
