# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1405 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.ncol=[[         4],]
input.temp=[[  0.25275054215293568E+003],]
input.invariants=[[  0.21128600594005778E+020,  0.16691594469264566E+020,  0.44370061247412132E+019,  0.32584070419935356E+017,  0.88195653685982036E+006,  0.59406006314894356E+008,  0.83003980071548715E+008,  0.11620315212019170E+013,],]
input.mtot=[[  0.21128600594005778E+020],]
input.rxt=[[ -0.98765432000000000E+008, -0.98765432000000000E+008,  0.15398353535569707E-011, -0.98765432000000000E+008,  0.38036040848335655E-011, -0.98765432000000000E+008,  0.14868106489433117E-011,],]
input.nfs=[[         8],]
input.rxntot=[[         7],]
input.inv_h2o_ndx=[[         4],]
input.t0=[[  0.30000000000000000E+003],]
input.usr_HO2_HO2_ndx=[[         2],]
input.usr_DMS_OH_ndx=[[         6],]
input.usr_SO2_OH_ndx=[[         4],]
# Output data is stored here.
output = Object()
output.rxt=[[ -0.98765432000000000E+008,  0.48397708835630720E-011,  0.15398353535569707E-011,  0.98908101107876037E-012,  0.38036040848335655E-011,  0.11621169696335625E-010,  0.14868106489433117E-011,],]
