# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1400 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.ncol=[[         4],]
input.temp=[[  0.25467953091539104E+003],]
input.invariants=[[  0.20940118452003353E+020,  0.16542693577082649E+020,  0.43974248749207040E+019,  0.40188888258798576E+017,  0.87066543281925132E+006,  0.58527839301260136E+008,  0.82044688443242162E+008,  0.11516490274022395E+013,],]
input.mtot=[[  0.20940118452003353E+020],]
input.rxt=[[ -0.98765432000000000E+008, -0.98765432000000000E+008,  0.15472361661442993E-011, -0.98765432000000000E+008,  0.38303697666388348E-011, -0.98765432000000000E+008,  0.14638214844285966E-011,],]
input.nfs=[[         8],]
input.rxntot=[[         7],]
input.inv_h2o_ndx=[[         4],]
input.t0=[[  0.30000000000000000E+003],]
input.usr_HO2_HO2_ndx=[[         2],]
input.usr_DMS_OH_ndx=[[         6],]
input.usr_SO2_OH_ndx=[[         4],]
# Output data is stored here.
output = Object()
output.rxt=[[ -0.98765432000000000E+008,  0.48744495464520509E-011,  0.15472361661442993E-011,  0.98083205664784414E-012,  0.38303697666388348E-011,  0.11326139509859181E-010,  0.14638214844285966E-011,],]
