# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1402 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.ncol=[[         4],]
input.temp=[[  0.25385187022866876E+003],]
input.invariants=[[  0.21007661278487249E+020,  0.16596052410004926E+020,  0.44116088684823219E+019,  0.36743423961447304E+017,  0.87487475914221921E+006,  0.58706988131269045E+008,  0.82403242427695170E+008,  0.11555843265646975E+013,],]
input.mtot=[[  0.21007661278487249E+020],]
input.rxt=[[ -0.98765432000000000E+008, -0.98765432000000000E+008,  0.15440701742534497E-011, -0.98765432000000000E+008,  0.38189124177561719E-011, -0.98765432000000000E+008,  0.14735987123445617E-011,],]
input.nfs=[[         8],]
input.rxntot=[[         7],]
input.inv_h2o_ndx=[[         4],]
input.t0=[[  0.30000000000000000E+003],]
input.usr_HO2_HO2_ndx=[[         2],]
input.usr_DMS_OH_ndx=[[         6],]
input.usr_SO2_OH_ndx=[[         4],]
# Output data is stored here.
output = Object()
output.rxt=[[ -0.98765432000000000E+008,  0.48558652133607861E-011,  0.15440701742534497E-011,  0.98422691595367391E-012,  0.38189124177561719E-011,  0.11455441859783901E-010,  0.14735987123445617E-011,],]
