# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1408 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.ncol=[[         4],]
input.temp=[[  0.25184386909617683E+003],]
input.invariants=[[  0.21240500047327990E+020,  0.16779995037389113E+020,  0.44605050099388774E+019,  0.30970179217205308E+017,  0.88867404519067612E+006,  0.60162055638045967E+008,  0.83567547082597002E+008,  0.11678681278297969E+013,],]
input.mtot=[[  0.21240500047327990E+020],]
input.rxt=[[ -0.98765432000000000E+008, -0.98765432000000000E+008,  0.15363300412890197E-011, -0.98765432000000000E+008,  0.37909475496612533E-011, -0.98765432000000000E+008,  0.14978640415709501E-011,],]
input.nfs=[[         8],]
input.rxntot=[[         7],]
input.inv_h2o_ndx=[[         4],]
input.t0=[[  0.30000000000000000E+003],]
input.usr_HO2_HO2_ndx=[[         2],]
input.usr_DMS_OH_ndx=[[         6],]
input.usr_SO2_OH_ndx=[[         4],]
# Output data is stored here.
output = Object()
output.rxt=[[ -0.98765432000000000E+008,  0.48816213675015754E-011,  0.15363300412890197E-011,  0.99319441927218710E-012,  0.37909475496612533E-011,  0.11751951984998154E-010,  0.14978640415709501E-011,],]
