# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1412 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.ncol=[[         4],]
input.temp=[[  0.25181704964517314E+003],]
input.invariants=[[  0.21223663825887019E+020,  0.16766694422450745E+020,  0.44569694034362737E+019,  0.32072542278845744E+017,  0.89084283962265309E+006,  0.59877965320798881E+008,  0.83700026350673363E+008,  0.11676999135807595E+013,],]
input.mtot=[[  0.21223663825887019E+020],]
input.rxt=[[ -0.98765432000000000E+008, -0.98765432000000000E+008,  0.15362260916029592E-011, -0.98765432000000000E+008,  0.37905724250880284E-011, -0.98765432000000000E+008,  0.14981934668032749E-011,],]
input.nfs=[[         8],]
input.rxntot=[[         7],]
input.inv_h2o_ndx=[[         4],]
input.t0=[[  0.30000000000000000E+003],]
input.usr_HO2_HO2_ndx=[[         2],]
input.usr_DMS_OH_ndx=[[         6],]
input.usr_SO2_OH_ndx=[[         4],]
# Output data is stored here.
output = Object()
output.rxt=[[ -0.98765432000000000E+008,  0.49190720523508634E-011,  0.15362260916029592E-011,  0.99308879900571303E-012,  0.37905724250880284E-011,  0.11755154468972258E-010,  0.14981934668032749E-011,],]
