# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1404 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.ncol=[[         4],]
input.temp=[[  0.25308585544715413E+003],]
input.invariants=[[  0.21088131919382995E+020,  0.16659624216312566E+020,  0.44285077030704287E+019,  0.33919259187435364E+017,  0.87959245907939167E+006,  0.59138987057081781E+008,  0.82804301453033328E+008,  0.11599215078558157E+013,],]
input.mtot=[[  0.21088131919382995E+020],]
input.rxt=[[ -0.98765432000000000E+008, -0.98765432000000000E+008,  0.15411273675214500E-011, -0.98765432000000000E+008,  0.38082724879197636E-011, -0.98765432000000000E+008,  0.14827634174715671E-011,],]
input.nfs=[[         8],]
input.rxntot=[[         7],]
input.inv_h2o_ndx=[[         4],]
input.t0=[[  0.30000000000000000E+003],]
input.usr_HO2_HO2_ndx=[[         2],]
input.usr_DMS_OH_ndx=[[         6],]
input.usr_SO2_OH_ndx=[[         4],]
# Output data is stored here.
output = Object()
output.rxt=[[ -0.98765432000000000E+008,  0.48473607261179706E-011,  0.15411273675214500E-011,  0.98756444723131767E-012,  0.38082724879197636E-011,  0.11571466760297166E-010,  0.14827634174715671E-011,],]
