# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1413 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.ncol=[[         4],]
input.temp=[[  0.25165448398307859E+003],]
input.invariants=[[  0.21236562765827723E+020,  0.16776884585003903E+020,  0.44596781808238218E+019,  0.31918396165716112E+017,  0.89209430873174593E+006,  0.59904116272822000E+008,  0.83798616041442513E+008,  0.11685290691101470E+013,],]
input.mtot=[[  0.21236562765827723E+020],]
input.rxt=[[ -0.98765432000000000E+008, -0.98765432000000000E+008,  0.15355956788245935E-011, -0.98765432000000000E+008,  0.37882976978591421E-011, -0.98765432000000000E+008,  0.15001933284562591E-011,],]
input.nfs=[[         8],]
input.rxntot=[[         7],]
input.inv_h2o_ndx=[[         4],]
input.t0=[[  0.30000000000000000E+003],]
input.usr_HO2_HO2_ndx=[[         2],]
input.usr_DMS_OH_ndx=[[         6],]
input.usr_SO2_OH_ndx=[[         4],]
# Output data is stored here.
output = Object()
output.rxt=[[ -0.98765432000000000E+008,  0.49304706857426726E-011,  0.15355956788245935E-011,  0.99374365725646217E-012,  0.37882976978591421E-011,  0.11777834014085245E-010,  0.15001933284562591E-011,],]
