# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1407 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.ncol=[[         4],]
input.temp=[[  0.25215295026150088E+003],]
input.invariants=[[  0.21203649650928914E+020,  0.16750883224233843E+020,  0.44527664266950717E+019,  0.30789680680541768E+017,  0.88644824955248681E+006,  0.59924495660455056E+008,  0.83380737163439721E+008,  0.11659278960492405E+013,],]
input.mtot=[[  0.21203649650928914E+020],]
input.rxt=[[ -0.98765432000000000E+008, -0.98765432000000000E+008,  0.15375269216026509E-011, -0.98765432000000000E+008,  0.37952675927051678E-011, -0.98765432000000000E+008,  0.14940778431155842E-011,],]
input.nfs=[[         8],]
input.rxntot=[[         7],]
input.inv_h2o_ndx=[[         4],]
input.t0=[[  0.30000000000000000E+003],]
input.usr_HO2_HO2_ndx=[[         2],]
input.usr_DMS_OH_ndx=[[         6],]
input.usr_SO2_OH_ndx=[[         4],]
# Output data is stored here.
output = Object()
output.rxt=[[ -0.98765432000000000E+008,  0.48435485213063165E-011,  0.15375269216026509E-011,  0.99180939103467770E-012,  0.37952675927051678E-011,  0.11707998373577533E-010,  0.14940778431155842E-011,],]
