# Data at [lat=   39.0553303768561      , lon=   262.904774388088      , k=          54 , time step=        1409 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.ncol=[[         4],]
input.temp=[[  0.25167660719924228E+003],]
input.invariants=[[  0.21257233527312499E+020,  0.16793214486576876E+020,  0.44640190407356247E+019,  0.32269311911188244E+017,  0.89007805981691577E+006,  0.60241573688024879E+008,  0.83679446805016592E+008,  0.11688472880587102E+013,],]
input.mtot=[[  0.21257233527312499E+020],]
input.rxt=[[ -0.98765432000000000E+008, -0.98765432000000000E+008,  0.15356815030196925E-011, -0.98765432000000000E+008,  0.37886073531076816E-011, -0.98765432000000000E+008,  0.14999208627353947E-011,],]
input.nfs=[[         8],]
input.rxntot=[[         7],]
input.inv_h2o_ndx=[[         4],]
input.t0=[[  0.30000000000000000E+003],]
input.usr_HO2_HO2_ndx=[[         2],]
input.usr_DMS_OH_ndx=[[         6],]
input.usr_SO2_OH_ndx=[[         4],]
# Output data is stored here.
output = Object()
output.rxt=[[ -0.98765432000000000E+008,  0.49426481341964905E-011,  0.15356815030196925E-011,  0.99390681891512445E-012,  0.37886073531076816E-011,  0.11775400066805676E-010,  0.14999208627353947E-011,],]
