# Data at [lat=  -13.2292708024991      , lon=   139.817062054960      , k=          51 , time step=         355 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.ncol=[[         4],]
input.rprddpsum=[[ 0.1176313812E-03],]
input.rprdshsum=[[ 0.0000000000E+00],]
input.evapcdpsum=[[ 0.3030048337E-04],]
input.evapcshsum=[[ 0.0000000000E+00],]
input.sflxbc=[[-0.7840839471E-14],]
input.sflxec=[[ 0.8032127231E-16],]
# Output data is stored here.
output = Object()
output.sflxbcdp=[[-0.7840839471E-14],]
output.sflxecdp=[[ 0.8032127231E-16],]
