# Data at [lat=  -13.2292708024991      , lon=   139.817062054960      , k=          51 , time step=         355 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.lphase=[[         2],]
input.imode=[[         1],]
# Output data is stored here.
output = Object()
output.sol_facti=[[ 0.6000000000E+00],]
output.sol_factic=[[ 0.0000000000E+00],]
output.sol_factb=[[ 0.0000000000E+00],]
output.f_act_conv=[[ 0.0000000000E+00],]
