# Data at [lat=  -13.2292708024991      , lon=   139.817062054960      , k=          51 , time step=         355 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.lspec=[[         1],]
input.imode=[[         1],]
input.lphase=[[         1],]
input.jaeronumb=[[         0],]
input.jaeromass=[[         1],]
input.jaerowater=[[         2],]
# Output data is stored here.
output = Object()
output.mm=[[        16],]
output.jnv=[[         2],]
output.jnummaswtr=[[         1],]
