# Data at [lat=  0.000000000000000E+000 , lon=  0.000000000000000E+000 , k=           0 , time step=           0 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.dgnum_amode=[[ 0.1100000000E-06, 0.2600000000E-07, 0.2000000000E-05, 0.5000000058E-07,],]
input.sigmag_amode=[[ 0.1800000000E+01, 0.1600000000E+01, 0.1800000000E+01, 0.1600000024E+01,],]
input.specdens_amode=[[ 0.1770000000E+04, 0.1797693135+309, 0.1797693135+309, 0.1000000000E+04, 0.1000000000E+04, 0.1700000000E+04, 0.1900000000E+04, 0.2600000000E+04, 0.1601000000E+04, 0.0000000000E+00, 0.0000000000E+00, 0.0000000000E+00, 0.0000000000E+00, 0.0000000000E+00,],]
input.lspectype_amode=[[         1,         4,         5,         6,         8,         7,         9,         0,         0,         0,         0,         0,         0,         0,         1,         5,         7,         9,         0,         0,         0,         0,         0,         0,         0,         0,         0,         0,         8,         7,         1,         6,         4,         5,         9,         0,         0,         0,         0,         0,         0,         0,         4,         6,         9,         0,         0,         0,         0,         0,         0,         0,         0,         0,         0,         0,],]
