# Data at [lat=   16.7209053140754      , lon=   95.1586611207219      , k=          55 , time step=        1415 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.airtemp=[[ 0.2801953538E+03],]
input.airprs=[[ 0.7684999273E+05],]
input.dgatk=[[ 0.7850593303E-07],]
input.dgacc=[[ 0.2226786509E-06],]
input.sgatk=[[ 0.1600000000E+01],]
input.sgacc=[[ 0.1800000000E+01],]
input.xxlsgat=[[ 0.4700036292E+00],]
input.xxlsgac=[[ 0.5877866649E+00],]
input.pdensat=[[ 0.1089825662E+04],]
input.pdensac=[[ 0.1098962399E+04],]
# Output data is stored here.
output = Object()
output.betaij0=[[ 0.3264182747E-14],]
output.betaii0=[[ 0.1052084325E-14],]
output.betajj0=[[ 0.7728003344E-15],]
output.betaij3=[[ 0.1674483533E-14],]
