# Data at [lat=   16.7209053140754      , lon=   95.1586611207219      , k=          55 , time step=        1415 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.lamda=[[ 0.8503779477E-07],]
input.kfmat=[[ 0.3263280274E-11],]
input.kfmac=[[ 0.3249686558E-11],]
input.kfmatac=[[ 0.3256462137E-11],]
input.knc=[[ 0.1473097262E-15],]
input.dgatk=[[ 0.7850593303E-07],]
input.dgacc=[[ 0.2226786509E-06],]
input.sgatk=[[ 0.1600000000E+01],]
input.sgacc=[[ 0.1800000000E+01],]
input.xxlsgat=[[ 0.4700036292E+00],]
input.xxlsgac=[[ 0.5877866649E+00],]
# Output data is stored here.
output = Object()
output.qn11=[[ 0.1052084325E-14],]
output.qn22=[[ 0.7728003344E-15],]
output.qn12=[[ 0.3264182747E-14],]
output.qv12=[[ 0.2189300702E-35],]
