# Data at [lat=   16.7209053140754      , lon=   95.1586611207219      , k=          55 , time step=        1415 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.deltat=[[ 0.3600000000E+04],]
input.ybetaij0=[[ 0.1076769936E-15, 0.8007481439E-16, 0.6893464879E-16,],]
input.ybetaii0=[[ 0.3470555599E-16, 0.3133876639E-16, 0.3470555599E-16,],]
input.ybetajj0=[[ 0.2549269545E-16, 0.2549269545E-16, 0.3133876639E-16,],]
input.qnum_bgn=[[ 0.3023400661E+11, 0.2472840448E+10, 0.4222424342E+07, 0.7177531211E+10, 0.0000000000E+00,],]
input.qnum_end=[[ 0.3023400661E+11, 0.2472840448E+10, 0.4222424342E+07, 0.7177531211E+10, 0.0000000000E+00,],]
# Output data is stored here.
output = Object()
output.qnum_end=[[ 0.3015034884E+11, 0.2438990539E+10, 0.4222424342E+07, 0.7109600652E+10, 0.0000000000E+00,],]
output.qnum_tavg=[[ 0.3019217772E+11, 0.2455915494E+10, 0.0000000000E+00, 0.7143565932E+10, 0.0000000000E+00,],]
