# Data at [lat=   45.1040729547578      , lon=   145.965088007967      , k=          68 , time step=         379 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.top_lev=[[         1],]
input.ncol=[[         4],]
input.imode=[[         1],]
input.nspec=[[         7],]
input.list_idx_in=[[         0],]
input.interstitial=[[ 0.4583718242E-09, 0.3364012337E-10, 0.1234964347E-09, 0.1189268029E-10, 0.9140768821E-12, 0.4861418100E-10, 0.4858920451E-11,],]
input.cldbrn=[[ 0.1083232612E-08, 0.6313224793E-10, 0.2231308116E-09, 0.2229957044E-10, 0.1635002136E-11, 0.9492576859E-10, 0.9410678414E-11,],]
input.density=[[ 0.1770000000E+04, 0.1000000000E+04, 0.1000000000E+04, 0.1700000000E+04, 0.2600000000E+04, 0.1900000000E+04, 0.1601000000E+04,],]
# Output data is stored here.
output = Object()
output.dryvol_a=[[ 0.4520722922E-12],]
output.dryvol_c=[[ 0.9678440582E-12],]
