# Data at [lat=   45.1040729547578      , lon=   145.965088007967      , k=          69 , time step=         378 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.top_lev=[[         1],]
input.ncol=[[         4],]
input.imode=[[         3],]
input.nspec=[[         7],]
input.list_idx_in=[[         0],]
input.interstitial=[[ 0.2441745358E-11, 0.3288397390E-09, 0.5764181687E-11, 0.1940943033E-12, 0.6465979594E-12, 0.3032516199E-11, 0.5434333699E-13,],]
input.cldbrn=[[ 0.6001970183E-11, 0.8394376080E-09, 0.1520848181E-10, 0.5019264358E-12, 0.1672809915E-11, 0.7843622239E-11, 0.1424130359E-12,],]
input.density=[[ 0.2600000000E+04, 0.1900000000E+04, 0.1770000000E+04, 0.1700000000E+04, 0.1000000000E+04, 0.1000000000E+04, 0.1601000000E+04,],]
# Output data is stored here.
output = Object()
output.dryvol_a=[[ 0.1810965101E-12],]
output.dryvol_c=[[ 0.4626107156E-12],]
