# Data at [lat=   45.1040729547578      , lon=   145.965088007967      , k=          68 , time step=         379 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.top_lev=[[         1],]
input.ncol=[[         4],]
input.imode=[[         3],]
input.nspec=[[         7],]
input.list_idx_in=[[         0],]
input.interstitial=[[ 0.3011544541E-11, 0.3960028639E-09, 0.6608937529E-11, 0.2251425548E-12, 0.7580229564E-12, 0.3560129394E-11, 0.6539466199E-13,],]
input.cldbrn=[[ 0.5622031502E-11, 0.7946059165E-09, 0.1355037187E-10, 0.4524734636E-12, 0.1526150650E-11, 0.7060745464E-11, 0.1338372801E-12,],]
input.density=[[ 0.2600000000E+04, 0.1900000000E+04, 0.1770000000E+04, 0.1700000000E+04, 0.1000000000E+04, 0.1000000000E+04, 0.1601000000E+04,],]
# Output data is stored here.
output = Object()
output.dryvol_a=[[ 0.2178061446E-12],]
output.dryvol_c=[[ 0.4369681904E-12],]
