# Data at [lat=   45.1040729547578      , lon=   145.965088007967      , k=          68 , time step=         379 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.top_lev=[[         1],]
input.ncol=[[         4],]
input.imode=[[         2],]
input.nspec=[[         4],]
input.list_idx_in=[[         0],]
input.interstitial=[[ 0.7232103877E-11, 0.1561038000E-11, 0.4573389632E-13, 0.3817644726E-14,],]
input.cldbrn=[[ 0.1317162806E-10, 0.1596756135E-11, 0.5428568670E-13, 0.4556957537E-14,],]
input.density=[[ 0.1770000000E+04, 0.1000000000E+04, 0.1900000000E+04, 0.1601000000E+04,],]
# Output data is stored here.
output = Object()
output.dryvol_a=[[ 0.5673427403E-14],]
output.dryvol_c=[[ 0.9069771640E-14],]
