# Data at [lat=   45.1040729547578      , lon=   145.965088007967      , k=          68 , time step=         379 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.top_lev=[[         1],]
input.ncol=[[         4],]
input.imode=[[         4],]
input.nspec=[[         3],]
input.list_idx_in=[[         0],]
input.interstitial=[[ 0.6026775036E-10, 0.2692401318E-10, 0.1396645841E-15,],]
input.cldbrn=[[ 0.1632349640E-26, 0.7326897587E-27, 0.3681943949E-32,],]
input.density=[[ 0.1000000000E+04, 0.1700000000E+04, 0.1601000000E+04,],]
# Output data is stored here.
output = Object()
output.dryvol_a=[[ 0.7610549241E-13],]
output.dryvol_c=[[ 0.2063345915E-29],]
