# Data at [lat=   45.1040729547578      , lon=   145.965088007967      , k=          69 , time step=         378 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.top_lev=[[         1],]
input.ncol=[[         4],]
input.imode=[[         1],]
# Output data is stored here.
output = Object()
output.dgncur=[[ 0.1100000000E-06],]
output.v2ncur=[[ 0.3031219160E+21],]
output.dryvol=[[ 0.0000000000E+00],]
