# Data at [lat=  -13.2292708024991      , lon=   139.817062054960      , k=          51 , time step=         355 ] 
# This file was generated by E3SM.

from math import nan as nan, inf as inf

# Object is just a dynamic container that stores input/output data.
class Object(object):
    pass
# Settings are stored here.
settings = Object()
# Input is stored here.
input = Object()
input.dt = [    0.00, ]
input.ncol=[[         4],]
input.temperature=[[ 0.2804261386E+03],]
input.pmid=[[ 0.6753476429E+05],]
input.pdel=[[ 0.3395589227E+04],]
input.cmfdqr=[[ 0.4201774770E-07],]
input.evapc=[[ 0.8237076572E-08],]
input.cldt=[[ 0.4131862680E-01],]
input.cldcu=[[ 0.4131862680E-01],]
input.cldst=[[ 0.0000000000E+00],]
input.evapr=[[ 0.7626064109E-09],]
input.prain=[[ 0.0000000000E+00],]
# Output data is stored here.
output = Object()
output.cldv=[[ 0.1917354367E+00],]
output.cldvcu=[[ 0.4289297744E-01],]
output.cldvst=[[ 0.3643593325E+00],]
output.rain=[[ 0.1351673886E-04],]
